// SPDX-License-Identifier: AGPL-3.0-only

package graphbuild

import (
	"context"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/globulario/sensei/golang/architecture/packcustody"
)

// The installed pack, as `sensei init` writes it into every project. Both
// synthetic repositories below get a byte-identical copy — that is the whole
// point: one stable identity, installed twice.
const installedPack = `# Meta-Principles.
#
# GENERATED by scripts/sync-principle-pack.py — do not edit by hand.
invariants:
  - id: meta.shared_one
    title: "Shared principle one"
    category: authority
    severity: critical
    status: active
    summary: |
      Installed shared knowledge with exactly one canonical author.
  - id: meta.shared_two
    title: "Shared principle two"
    category: authority
    severity: high
    status: active
    summary: |
      Also installed, also not the containing repository's to author.
`

// initializedRepo builds a checkout with its own knowledge plus an installed
// pack mirror. governed controls whether `sensei init`'s baseline is present.
func initializedRepo(t *testing.T, name, ownID string, governed bool) (root, corpus string) {
	t.Helper()
	root = filepath.Join(t.TempDir(), name)
	corpus = filepath.Join(root, "docs", "awareness")
	if err := os.MkdirAll(corpus, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, ".sensei"), 0o755); err != nil {
		t.Fatal(err)
	}

	own := "invariants:\n  - id: " + ownID + "\n    title: \"" + name + " own knowledge\"\n" +
		"    category: authority\n    severity: high\n    status: active\n" +
		"    summary: |\n      Genuinely authored by " + name + ".\n"
	if err := os.WriteFile(filepath.Join(corpus, "invariants.yaml"), []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(corpus, "meta_principles.yaml"), []byte(installedPack), 0o644); err != nil {
		t.Fatal(err)
	}

	if governed {
		var ir packcustody.InstallRecord
		ir.SchemaVersion = packcustody.ReceiptSchemaVersion
		ir.Kind = packcustody.InstallKind
		ir.PackDigest = packcustody.Digest([]byte(installedPack))
		b, err := yaml.Marshal(ir)
		if err != nil {
			t.Fatal(err)
		}
		p := packcustody.InstallRecordFilePath(root)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root, corpus
}

func compileRepo(t *testing.T, domain, corpus, custodyRoot string) Compilation {
	t.Helper()
	comp, err := Compile(context.Background(), CompileRequest{
		Sources: []SourceRoot{{
			FilesystemPath:   corpus,
			IdentityRoot:     corpus,
			RepositoryDomain: domain,
			CustodyRoot:      custodyRoot,
		}},
	})
	if err != nil {
		t.Fatalf("compile %s: %v", domain, err)
	}
	return comp
}

var (
	subjectRE    = regexp.MustCompile(`^(<[^>]+>)\s`)
	authoredInRE = regexp.MustCompile(`^(<[^>]+>)\s+<https://globular\.io/awareness#authoredIn>\s+"([^"]*)"`)
)

// authoringDomains derives, for each stable subject, the set of repository
// domains that PUBLISHED it — from aw:authoredIn (which source document emitted
// the subject) mapped through the domain that compiled that document.
//
// It deliberately does not read aw:repo. The acceptance criterion for this
// defect says so explicitly, and the reason is that aw:repo is itself writable
// graph content: a corpus that lies about its own owner would satisfy a check
// built on it while still colliding. Publication provenance is the independent
// fact.
func authoringDomains(t *testing.T, comps map[string]Compilation) map[string]map[string]bool {
	t.Helper()
	out := map[string]map[string]bool{}
	for domain, comp := range comps {
		for _, line := range strings.Split(string(comp.CanonicalNTriples), "\n") {
			m := authoredInRE.FindStringSubmatch(line)
			if m == nil {
				continue
			}
			subject := m[1]
			if out[subject] == nil {
				out[subject] = map[string]bool{}
			}
			out[subject][domain] = true
		}
	}
	return out
}

// TestNoStableSubjectHasTwoAuthoritativeAuthoringDomains is the mechanical
// regression for #178: publishing two Sensei-initialized repositories that share
// one store must not produce a single identity with two authors.
//
// It asserts over EVERY stable subject rather than over the pack's ids, because
// a check that only looked at meta.* would pass while the same collision
// reappeared under any other shared-knowledge class installed the same way.
func TestNoStableSubjectHasTwoAuthoritativeAuthoringDomains(t *testing.T) {
	rootA, corpusA := initializedRepo(t, "alpha", "alpha.own", true)
	rootB, corpusB := initializedRepo(t, "beta", "beta.own", true)

	comps := map[string]Compilation{
		"github.com/example/alpha": compileRepo(t, "github.com/example/alpha", corpusA, rootA),
		"github.com/example/beta":  compileRepo(t, "github.com/example/beta", corpusB, rootB),
	}

	var offenders []string
	for subject, domains := range authoringDomains(t, comps) {
		if len(domains) > 1 {
			names := make([]string, 0, len(domains))
			for d := range domains {
				names = append(names, d)
			}
			offenders = append(offenders, subject+" authored by "+strings.Join(names, " + "))
		}
	}
	if len(offenders) > 0 {
		t.Fatalf("stable subjects with more than one authoritative authoring domain:\n  %s",
			strings.Join(offenders, "\n  "))
	}

	// Guard against the check passing for the wrong reason: each repository must
	// still publish its OWN knowledge. A build that published nothing would
	// trivially satisfy the invariant above.
	for domain, comp := range comps {
		if !strings.Contains(string(comp.CanonicalNTriples), ".own>") {
			t.Errorf("%s published none of its own knowledge; the invariant above proved nothing", domain)
		}
	}
}

// Proof that the test above is testing the mechanism and not an accident of the
// fixture: with custody derivation switched off, the SAME two repositories DO
// collide on the installed pack. Without this, a fixture that happened never to
// share an identity would make the invariant look enforced when nothing enforced
// it — the failure mode where a green regression test is itself the bug.
func TestTheCollisionIsRealWhenCustodyDerivationIsOff(t *testing.T) {
	_, corpusA := initializedRepo(t, "alpha", "alpha.own", true)
	_, corpusB := initializedRepo(t, "beta", "beta.own", true)

	comps := map[string]Compilation{
		// Custody root deliberately empty: the pre-fix behaviour.
		"github.com/example/alpha": compileRepo(t, "github.com/example/alpha", corpusA, ""),
		"github.com/example/beta":  compileRepo(t, "github.com/example/beta", corpusB, ""),
	}

	var collided []string
	for subject, domains := range authoringDomains(t, comps) {
		if len(domains) > 1 && strings.Contains(subject, "meta.shared_") {
			collided = append(collided, subject)
		}
	}
	if len(collided) == 0 {
		t.Fatal("expected the installed pack to be co-authored when custody derivation is off; " +
			"if this no longer reproduces, the regression above is not proving anything")
	}
}

// The exclusion must be reported, not silent. Knowledge vanishing quietly and
// knowledge deliberately left to its owner are indistinguishable to an operator
// unless the build says which happened.
func TestSharedProjectionExclusionIsReportedWithItsEvidence(t *testing.T) {
	root, corpus := initializedRepo(t, "alpha", "alpha.own", true)
	comp := compileRepo(t, "github.com/example/alpha", corpus, root)

	excluded := comp.ImportReport.CustodyExcluded()
	if len(excluded) != 1 {
		t.Fatalf("custody-excluded files = %d, want 1", len(excluded))
	}
	if got := excluded[0].Status; got != "shared_custody" {
		t.Fatalf("status = %q, want shared_custody", got)
	}
	if !strings.Contains(excluded[0].Reason, "install record") {
		t.Fatalf("exclusion does not carry its evidence: %q", excluded[0].Reason)
	}
	if comp.ImportReport.HasCustodyRefusal() {
		t.Fatal("a governed projection is not a refusal")
	}

	// The disposition is also recorded durably in the source manifest, so the
	// decision survives the build that made it.
	var found bool
	for _, e := range comp.SourceManifest.Sources {
		if strings.HasSuffix(e.LogicalPath, "meta_principles.yaml") {
			found = true
			if e.Disposition != "shared_custody" {
				t.Errorf("manifest disposition = %q, want shared_custody", e.Disposition)
			}
		}
	}
	if !found {
		t.Error("the excluded document is absent from the source manifest; the exclusion left no record")
	}
}

// An ungoverned legacy mirror is refused, and the refusal is typed distinctly
// from a governed exclusion so an operator can tell "not mine" from "unknown".
func TestUngovernedMirrorIsTypedAsARefusal(t *testing.T) {
	root, corpus := initializedRepo(t, "legacy", "legacy.own", false)
	comp := compileRepo(t, "github.com/example/legacy", corpus, root)

	if !comp.ImportReport.HasCustodyRefusal() {
		t.Fatal("a mirror with no governed provenance must be refused, not attributed")
	}
	excluded := comp.ImportReport.CustodyExcluded()
	if len(excluded) != 1 || excluded[0].Status != "custody_refused" {
		t.Fatalf("expected exactly one custody_refused entry, got %+v", excluded)
	}

	// Refused content is published by nobody: it must not reach the graph under
	// this repository's name.
	if strings.Contains(string(comp.CanonicalNTriples), "meta.shared_one") {
		t.Fatal("refused content was published anyway")
	}
}

// Without a custody root the build behaves exactly as it always did. This keeps
// the change from silently altering every existing caller — seed builds, foreign
// imports, and the whole-graph path all compile unchanged.
func TestWithoutCustodyRootBehaviourIsUnchanged(t *testing.T) {
	_, corpus := initializedRepo(t, "alpha", "alpha.own", true)
	comp := compileRepo(t, "github.com/example/alpha", corpus, "")

	if len(comp.ImportReport.CustodyExcluded()) != 0 {
		t.Fatal("custody derivation must be inert when no custody root is supplied")
	}
	if !strings.Contains(string(comp.CanonicalNTriples), "meta.shared_one") {
		t.Fatal("historical behaviour imports the mirror; it must still do so")
	}
	_ = subjectRE
}
