// SPDX-License-Identifier: AGPL-3.0-only

package coldsource

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/globulario/awareness-graph/golang/extractor"
	"gopkg.in/yaml.v3"
)

// Report is the candidate-mining scoring sheet. The funnel counts make it obvious
// where candidates are lost; the per-candidate rows carry blank manual-review
// labels for the human scoring pass that decides the go/no-go.
type Report struct {
	Range                   string
	Drafter                 string // "echo" | "llm:<model>"
	TotalSignals            int
	Themes                  int
	TriangulatedThemes      int
	HeldBackSingleSource    int
	Drafted                 int // drafts attempted (one per triangulated theme)
	RejectedMalformed       int // unparseable / unknown-class model output
	RejectedMissingCitation int // no/fabricated citation (ValidateDraft contract)
	RejectedShallow         int
	RejectedDuplicate       int
	RejectedUnresolved      int // GROUND: all evidence unresolved / claimed symbol absent
	SegregatedReviewOnly    int // GROUND: only review-discussion evidence (a lead, not an invariant)
	SkippedNoDraft          int // stdin: triangulated bundle had no submitted draft (expected)
	CandidatesEmitted       int // files actually written (0 in dry-run)
	Cap                     int // top-N bound applied
	Dropped                 int // admissible candidates beyond the cap
	DryRun                  bool
	WindowPlan              string // auto-window selection note (empty if fixed --since)
	Candidates              []CandidateSummary
	ReviewOnlyLeads         []CandidateSummary // segregated by GROUND — not invariants, surfaced for the human
}

// CandidateSummary is one admissible candidate, with a blank manual-review
// label for the scoring pass: load-bearing | shallow | wrong | duplicate.
type CandidateSummary struct {
	CandidateID    string
	Class          string
	Theme          string
	Confidence     string
	Citations      []string
	Reason         string
	ReviewLabel    string // filled by the human reviewer
	Tier           string // GROUND provenance: test_encoded|landed_commit|review_suggestion|unresolved
	Drift          bool   // a cited symbol was found, but far from the cited line
	SymbolMismatch bool   // a resolving file citation held none of the claimed symbols
}

// candidateYAML is the on-disk shape under candidates/. status is ALWAYS
// "candidate"; promoted_from records the cold-source origin. review_label is
// blank for the human to fill. Nothing here is active knowledge.
type candidateYAML struct {
	ID                string   `yaml:"id"`
	Class             string   `yaml:"class"`
	Status            string   `yaml:"status"`
	PromotedFrom      string   `yaml:"promoted_from"`
	Theme             string   `yaml:"theme"`
	Reason            string   `yaml:"reason"`
	Confidence        string   `yaml:"confidence"`
	ActivationTrigger string   `yaml:"activation_trigger,omitempty"`
	RequiredTests     []string `yaml:"required_tests,omitempty"`
	SourcePaths       []string `yaml:"source_paths"`
	ReviewLabel       string   `yaml:"review_label"` // load-bearing|shallow|wrong|duplicate
}

const candidateHeader = "# Cold-source candidate — NOT YET active knowledge.\n" +
	"# Generated by `awg cold-bootstrap`. status:candidate, never auto-promoted.\n" +
	"# Review: set review_label to load-bearing | shallow | wrong | duplicate.\n"

// EmitCandidate writes one candidate YAML to <outDir>/<class>/<id>.yaml. It
// writes NOWHERE else and never marks a node active. Returns the written path.
func EmitCandidate(outDir string, p *extractor.PromotionProposal) (string, error) {
	// Cage guard: this package writes candidates and ONLY candidates. Refuse any
	// output path that is not under a candidates/ tree, so cold-source can never
	// overwrite active knowledge (invariants/, failure_modes/, the seed, ...).
	if !underCandidatesDir(outDir) {
		return "", fmt.Errorf("refusing to emit outside a candidates/ tree (got %q): cold-source writes candidates only", outDir)
	}
	cy := candidateYAML{
		ID:                p.CandidateID,
		Class:             p.CandidateClass,
		Status:            "candidate",
		PromotedFrom:      "cold_source",
		Theme:             p.Theme,
		Reason:            p.Reason,
		Confidence:        p.Confidence,
		ActivationTrigger: p.ActivationTrigger,
		RequiredTests:     p.RequiredTests,
		SourcePaths:       p.SourcePaths,
		ReviewLabel:       "",
	}
	dir := filepath.Join(outDir, classDir(p.CandidateClass))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, sanitizeID(p.CandidateID)+".yaml")
	data, err := yaml.Marshal(cy)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, append([]byte(candidateHeader), data...), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// classDir maps a candidate class to its subdirectory, e.g.
// "ForbiddenFixCandidate" -> "forbidden_fix".
func classDir(class string) string {
	c := strings.ToLower(strings.TrimSpace(class))
	c = strings.TrimSuffix(c, "candidate")
	c = strings.TrimSuffix(c, "_")
	switch c {
	case "forbiddenfix":
		return "forbidden_fix"
	case "failuremode":
		return "failure_mode"
	case "implementationpattern":
		return "implementation_pattern"
	case "authoritydomain":
		return "authority_domain"
	case "runtimeevidence":
		return "runtime_evidence"
	case "repairplan":
		return "repair_plan"
	case "":
		return "unclassified"
	default:
		return c
	}
}

// underCandidatesDir reports whether dir has a path element named "candidates".
// The cage: cold-source may only ever write under a candidates/ tree.
func underCandidatesDir(dir string) bool {
	for _, seg := range strings.Split(filepath.ToSlash(filepath.Clean(dir)), "/") {
		if seg == "candidates" {
			return true
		}
	}
	return false
}

func sanitizeID(id string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(id) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '.', r == '_', r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		return "unnamed"
	}
	return s
}

// RenderReport prints the scoring sheet. Deterministic and bounded.
func RenderReport(w io.Writer, r Report) {
	fmt.Fprintf(w, "\nAWG cold-bootstrap — candidate mining report\n")
	fmt.Fprintf(w, "===========================================\n")
	if r.Range != "" {
		fmt.Fprintf(w, "git range:                 %s\n", r.Range)
	}
	if r.WindowPlan != "" {
		fmt.Fprintf(w, "window plan:               %s\n", r.WindowPlan)
	}
	if r.Drafter != "" {
		fmt.Fprintf(w, "drafter:                   %s\n", r.Drafter)
	}
	mode := "WRITE"
	if r.DryRun {
		mode = "DRY-RUN (no files written)"
	}
	fmt.Fprintf(w, "mode:                      %s\n\n", mode)
	fmt.Fprintf(w, "Funnel\n")
	fmt.Fprintf(w, "  total signals found:      %d\n", r.TotalSignals)
	fmt.Fprintf(w, "  themes found:             %d\n", r.Themes)
	fmt.Fprintf(w, "  triangulated themes:      %d\n", r.TriangulatedThemes)
	fmt.Fprintf(w, "  held back (single-source):%d\n", r.HeldBackSingleSource)
	fmt.Fprintf(w, "  drafts attempted:         %d\n", r.Drafted)
	fmt.Fprintf(w, "  rejected (malformed):     %d\n", r.RejectedMalformed)
	fmt.Fprintf(w, "  rejected (no citation):   %d\n", r.RejectedMissingCitation)
	fmt.Fprintf(w, "  rejected (shallow):       %d\n", r.RejectedShallow)
	fmt.Fprintf(w, "  rejected (duplicate):     %d\n", r.RejectedDuplicate)
	fmt.Fprintf(w, "  rejected (unresolved):    %d\n", r.RejectedUnresolved)
	fmt.Fprintf(w, "  segregated (review-only): %d\n", r.SegregatedReviewOnly)
	if r.SkippedNoDraft > 0 {
		fmt.Fprintf(w, "  skipped (no draft):       %d\n", r.SkippedNoDraft)
	}
	fmt.Fprintf(w, "  candidates accepted:      %d\n", len(r.Candidates))
	if r.Cap > 0 {
		fmt.Fprintf(w, "  bound (top-N cap):        %d\n", r.Cap)
		fmt.Fprintf(w, "  dropped beyond cap:       %d\n", r.Dropped)
	}
	if !r.DryRun {
		fmt.Fprintf(w, "  candidates emitted:       %d\n", r.CandidatesEmitted)
	}

	// Nothing to review ONLY when there are neither accepted candidates NOR
	// segregated review-only leads. The previous empty-candidates early return
	// hid review-only leads whenever 0 candidates were accepted — a run that
	// produced only leads silently showed nothing.
	if len(r.Candidates) == 0 && len(r.ReviewOnlyLeads) == 0 {
		fmt.Fprintf(w, "\n(no admissible candidates — nothing to review)\n")
		return
	}
	if len(r.Candidates) == 0 {
		fmt.Fprintf(w, "\n(no accepted candidates — review-only leads were segregated; see below)\n")
	}

	if len(r.Candidates) > 0 {
		fmt.Fprintf(w, "\nScoring sheet (label each: load-bearing | shallow | wrong | duplicate)\n")
		fmt.Fprintf(w, "%-3s %-12s %-40s %-7s %-4s %-14s %s\n", "#", "class", "theme", "conf", "cits", "ground", "label")
		fmt.Fprintf(w, "%s\n", strings.Repeat("-", 104))
		for i, c := range r.Candidates {
			label := c.ReviewLabel
			if label == "" {
				label = "______"
			}
			ground := c.Tier
			if ground == "" {
				ground = "-"
			}
			if c.SymbolMismatch {
				ground += "!" // resolving file citation held none of the claimed symbols
			} else if c.Drift {
				ground += "~" // symbol found, but the cited line moved
			}
			fmt.Fprintf(w, "%-3d %-12s %-40s %-7s %-4d %-14s %s\n",
				i+1, classDir(c.Class), truncate(c.Theme, 40), c.Confidence, len(c.Citations), ground, label)
		}
		// Per-candidate evidence so a reviewer can label go/no-go from the report
		// alone (dry-run needs no files on disk). Citations are bounded per
		// candidate to keep the report readable.
		fmt.Fprintf(w, "\nCandidate evidence (for labeling)\n")
		for i, c := range r.Candidates {
			fmt.Fprintf(w, "\n[%d] %s  (class=%s conf=%s)\n", i+1, c.Theme, classDir(c.Class), c.Confidence)
			fmt.Fprintf(w, "    reason: %s\n", c.Reason)
			fmt.Fprintf(w, "    citations (%d):\n", len(c.Citations))
			const maxShown = 8
			for j, cit := range c.Citations {
				if j >= maxShown {
					fmt.Fprintf(w, "      … and %d more\n", len(c.Citations)-maxShown)
					break
				}
				fmt.Fprintf(w, "      - %s\n", cit)
			}
		}
	}

	// Review-only leads: GROUND segregated these — their only evidence is a PR
	// discussion (or a commit unrelated to the cited files). They are NOT
	// invariants the tree encodes, so they never enter the accepted set; they are
	// surfaced as leads about where a rule MIGHT belong, pending real evidence.
	if len(r.ReviewOnlyLeads) > 0 {
		fmt.Fprintf(w, "\nReview-only leads (segregated — proposed in review, not encoded in the tree)\n")
		for i, c := range r.ReviewOnlyLeads {
			fmt.Fprintf(w, "  [%d] %s  (class=%s) — %d citation(s); re-derive against the tree before trusting\n",
				i+1, c.Theme, classDir(c.Class), len(c.Citations))
		}
	}

	fmt.Fprintf(w, "\nGround tier: test_encoded > landed_commit > review_suggestion > unresolved")
	fmt.Fprintf(w, "  (! = claimed symbol absent at cited file; ~ = cited line drifted)\n")
	fmt.Fprintf(w, "Success criterion: continue only if ≳30%% are 'load-bearing' with low 'wrong'.\n")
}
