// SPDX-License-Identifier: AGPL-3.0-only

package resultpipeline

import (
	"github.com/globulario/sensei/golang/architecture"
	"github.com/globulario/sensei/golang/architecture/closure"
	"github.com/globulario/sensei/golang/architecture/factextract"
	"github.com/globulario/sensei/golang/architecture/maintenance"
	"github.com/globulario/sensei/golang/architecture/proofrequirements"
	"github.com/globulario/sensei/golang/architecture/questiongen"
)

// resultInferenceProfile is the fixed, versioned result-local inference profile
// (spec §10): documentation and test facts are included; raw Git history and
// mutation analysis are excluded because they are not result-tree-local and can
// change independently of the exact result; candidate confidence floor is low.
func resultInferenceProfile(root string) factextract.Options {
	return factextract.Options{
		Repo:                    root,
		Format:                  "json",
		IncludeDocs:             true,
		IncludeTests:            true,
		IncludeHistory:          false,
		IncludeMutationAnalysis: false,
		MinimumConfidence:       "low",
	}
}

// emptyResultEvidenceState is the explicit empty, result-bound evidence
// projection (spec §12/§14): prior evidence bound to another result is not
// applicable, and its absence is expressed as an empty current-result state
// rather than omitted.
func emptyResultEvidenceState(binding architecture.ClaimDocumentBinding) *maintenance.EvidenceStateDocument {
	return &maintenance.EvidenceStateDocument{
		SchemaVersion: "1",
		GeneratedBy:   "sensei.resultpipeline",
		Binding:       binding,
	}
}

// emptyResultDialogue is the explicit empty, result-bound dialogue the pipeline
// starts from (spec §14): a base-bound dialogue is never silently rebound; fresh
// architect questions are generated by the architect-questions stage.
func emptyResultDialogue(binding architecture.ClaimDocumentBinding) *architecture.DialogueDocument {
	return &architecture.DialogueDocument{
		SchemaVersion: "1",
		CompiledBy:    "sensei.resultpipeline",
		Binding:       binding,
		OpenQuestions: []architecture.OpenQuestion{},
	}
}

// ProofRequirementDocument is the stage-9 canonical output: the current task
// proof requirements derived from the result graph, closure, admission, and
// architect questions. An empty requirement set is an explicit computed result,
// never an omitted artifact.
type ProofRequirementDocument struct {
	SchemaVersion string `json:"schema_version" yaml:"schema_version"`
	GeneratedBy   string `json:"generated_by" yaml:"generated_by"`

	// Completeness is a closed vocabulary: "complete" only when admission, graph,
	// closure, and architect-question inputs were all consulted and no unresolved
	// extraction limitation remains; "blocked" when a required input was not
	// consulted or an architect decision remains unresolved; "uncertifiable" when
	// closure itself is uncertifiable. An incomplete extraction must never
	// serialize as a complete empty requirement set.
	Completeness string `json:"completeness" yaml:"completeness"`

	ResultBindingDigestSHA256             string `json:"result_binding_digest_sha256" yaml:"result_binding_digest_sha256"`
	SourceAdmissionDecisionDigestSHA256   string `json:"source_admission_decision_digest_sha256,omitempty" yaml:"source_admission_decision_digest_sha256,omitempty"`
	SourceAuthorityResolutionDigestSHA256 string `json:"source_authority_resolution_digest_sha256,omitempty" yaml:"source_authority_resolution_digest_sha256,omitempty"`
	SourceGraphDigestSHA256               string `json:"source_graph_digest_sha256" yaml:"source_graph_digest_sha256"`
	SourceClosureDigestSHA256             string `json:"source_closure_digest_sha256" yaml:"source_closure_digest_sha256"`
	SourceQuestionsDigestSHA256           string `json:"source_questions_digest_sha256" yaml:"source_questions_digest_sha256"`

	Obligations                 []proofrequirements.Obligation `json:"obligations" yaml:"obligations"`
	RequiredTests               []string                       `json:"required_tests" yaml:"required_tests"`
	ForbiddenMoves              []string                       `json:"forbidden_moves" yaml:"forbidden_moves"`
	UnresolvedArchitectQuestion []string                       `json:"unresolved_architect_questions" yaml:"unresolved_architect_questions"`
	Limitations                 []string                       `json:"limitations" yaml:"limitations"`
}

const (
	ProofComplete      = "complete"
	ProofBlocked       = "blocked"
	ProofUncertifiable = "uncertifiable"
)

// ArchitectQuestionsBundle is the stage-8 canonical output: the result-bound
// dialogue, the generation report, and exact, set-based blocker accounting. When
// no question is warranted it still exists with GeneratedCount 0 and
// AllBlockersAccountedFor true — the absence of open questions is a produced,
// verifiable fact. Accounting is by exact blocker-ID set, never by count:
// every current closure blocker must have exactly one current disposition, and
// historical no_longer_backed questions never satisfy a current blocker.
type ArchitectQuestionsBundle struct {
	Dialogue               architecture.DialogueDocument `json:"dialogue" yaml:"dialogue"`
	Report                 questiongen.Report            `json:"report" yaml:"report"`
	GeneratedCount         int                           `json:"generated_count" yaml:"generated_count"`
	ArchitectRequiredCount int                           `json:"architect_required_count" yaml:"architect_required_count"`

	CurrentBlockerIDs        []string `json:"current_blocker_ids" yaml:"current_blocker_ids"`
	AccountedBlockerIDs      []string `json:"accounted_blocker_ids" yaml:"accounted_blocker_ids"`
	UnaccountedBlockerIDs    []string `json:"unaccounted_blocker_ids" yaml:"unaccounted_blocker_ids"`
	DuplicateAccountingIDs   []string `json:"duplicate_accounting_ids" yaml:"duplicate_accounting_ids"`
	HistoricalNoLongerBacked []string `json:"historical_questions_no_longer_backed" yaml:"historical_questions_no_longer_backed"`
	UnsupportedCritical      []string `json:"unsupported_critical_blockers" yaml:"unsupported_critical_blockers"`

	AllBlockersAccountedFor      bool `json:"all_blockers_accounted_for" yaml:"all_blockers_accounted_for"`
	ArchitectQuestionsActionable bool `json:"architect_questions_actionable" yaml:"architect_questions_actionable"`
}

// InferredClaimsBundle is the stage-4 canonical output: the normalized result
// claim document plus the extraction limitations that shaped it.
type InferredClaimsBundle struct {
	Document    architecture.ClaimDocument `json:"document" yaml:"document"`
	Limitations []architecture.Limitation  `json:"limitations,omitempty" yaml:"limitations,omitempty"`
}

// MaintainedClaimsBundle is the stage-5 canonical output.
type MaintainedClaimsBundle struct {
	Document architecture.ClaimDocument `json:"document" yaml:"document"`
	Report   any                        `json:"report" yaml:"report"`
}

// closureScopeFromRequest preserves the task scope while rebinding the repository
// snapshot and graph to the exact result (spec §15).
func closureScopeFromRequest(base closure.Scope, domain string) closure.Scope {
	if base.Domain == "" {
		base.Domain = domain
	}
	return base
}
