// SPDX-License-Identifier: Apache-2.0

package resultpipeline

import (
	"github.com/globulario/sensei/golang/architecture"
	"github.com/globulario/sensei/golang/architecture/factextract"
	"github.com/globulario/sensei/golang/architecture/maintenance"
	"github.com/globulario/sensei/golang/architecture/proofrequirements"
	"github.com/globulario/sensei/golang/architecture/questiongen"
)

// resultInferenceProfile is the fixed, versioned result-local inference profile
// (spec §10): documentation and test facts are included; raw Git history and
// mutation analysis are excluded because they are not result-tree-local and can
// change independently of the exact result; candidate confidence floor is low.
func resultInferenceProfile(root string) factextract.Options {
	return factextract.Options{
		Repo:                    root,
		Format:                  "json",
		IncludeDocs:             true,
		IncludeTests:            true,
		IncludeHistory:          false,
		IncludeMutationAnalysis: false,
		MinimumConfidence:       "low",
	}
}

// emptyResultEvidenceState is the explicit empty, result-bound evidence
// projection (spec §12/§14): prior evidence bound to another result is not
// applicable, and its absence is expressed as an empty current-result state
// rather than omitted.
func emptyResultEvidenceState(binding architecture.ClaimDocumentBinding) *maintenance.EvidenceStateDocument {
	return &maintenance.EvidenceStateDocument{
		SchemaVersion: "1",
		GeneratedBy:   "sensei.resultpipeline",
		Binding:       binding,
	}
}

// emptyResultDialogue is the explicit empty, result-bound dialogue the pipeline
// starts from (spec §14): a base-bound dialogue is never silently rebound; fresh
// architect questions are generated by the architect-questions stage.
func emptyResultDialogue(binding architecture.ClaimDocumentBinding) *architecture.DialogueDocument {
	return &architecture.DialogueDocument{
		SchemaVersion: "1",
		CompiledBy:    "sensei.resultpipeline",
		Binding:       binding,
		OpenQuestions: []architecture.OpenQuestion{},
	}
}

// ProofRequirementDocument is the stage-9 canonical output. Its single
// definition lives in the proofrequirements package (proofrequirements.Compose
// builds it from the seven authoritative sources); the pipeline consumes it under
// this local name so there is exactly one document shape and one composer.
type ProofRequirementDocument = proofrequirements.Document

// Extraction-completeness and proving-disposition vocabularies are re-exported
// from the composer package so existing pipeline references keep working against
// one source of truth.
const (
	ExtractionComplete      = proofrequirements.ExtractionComplete
	ExtractionIncomplete    = proofrequirements.ExtractionIncomplete
	ExtractionUncertifiable = proofrequirements.ExtractionUncertifiable

	ProvingReady         = proofrequirements.ProvingReady
	ProvingBlocked       = proofrequirements.ProvingBlocked
	ProvingUncertifiable = proofrequirements.ProvingUncertifiable
)

// ArchitectQuestionsBundle is the stage-8 canonical output: the result-bound
// dialogue, the generation report, and exact, set-based blocker accounting. When
// no question is warranted it still exists with GeneratedCount 0 and
// AllBlockersAccountedFor true — the absence of open questions is a produced,
// verifiable fact. Accounting is by exact blocker-ID set, never by count:
// every current closure blocker must have exactly one current disposition, and
// historical no_longer_backed questions never satisfy a current blocker.
type ArchitectQuestionsBundle struct {
	Dialogue               architecture.DialogueDocument `json:"dialogue" yaml:"dialogue"`
	Report                 questiongen.Report            `json:"report" yaml:"report"`
	GeneratedCount         int                           `json:"generated_count" yaml:"generated_count"`
	ArchitectRequiredCount int                           `json:"architect_required_count" yaml:"architect_required_count"`

	CurrentBlockerIDs        []string `json:"current_blocker_ids" yaml:"current_blocker_ids"`
	AccountedBlockerIDs      []string `json:"accounted_blocker_ids" yaml:"accounted_blocker_ids"`
	UnaccountedBlockerIDs    []string `json:"unaccounted_blocker_ids" yaml:"unaccounted_blocker_ids"`
	DuplicateAccountingIDs   []string `json:"duplicate_accounting_ids" yaml:"duplicate_accounting_ids"`
	HistoricalNoLongerBacked []string `json:"historical_questions_no_longer_backed" yaml:"historical_questions_no_longer_backed"`
	UnsupportedCritical      []string `json:"unsupported_critical_blockers" yaml:"unsupported_critical_blockers"`

	AllBlockersAccountedFor      bool `json:"all_blockers_accounted_for" yaml:"all_blockers_accounted_for"`
	ArchitectQuestionsActionable bool `json:"architect_questions_actionable" yaml:"architect_questions_actionable"`
}

// InferredClaimsBundle is the stage-4 canonical output: the normalized result
// claim document plus the extraction limitations that shaped it.
type InferredClaimsBundle struct {
	Document    architecture.ClaimDocument `json:"document" yaml:"document"`
	Limitations []architecture.Limitation  `json:"limitations,omitempty" yaml:"limitations,omitempty"`
}

// MaintainedClaimsBundle is the stage-5 canonical output.
type MaintainedClaimsBundle struct {
	Document architecture.ClaimDocument `json:"document" yaml:"document"`
	Report   any                        `json:"report" yaml:"report"`
}
