// awareness_graph.proto — gRPC contract for the awareness graph service.
//
// Design rules:
//   - Briefing is the primary consumer surface. It returns prose composed
//     from SPARQL results — a single tool agents call instead of 200.
//   - Impact is the structured equivalent: same data shape as Briefing but
//     returned as typed nodes rather than narration. Used by code review
//     tools, the pre-commit guard, etc.
//   - Query is raw SPARQL passthrough — admin/debug only, RBAC-gated.
//     Not exposed to MCP tools by default; intended for the operator CLI.
//   - Resolve is a single-node lookup for following annotation IDs in code
//     (// @invariant: X) back to their full triple set.
//
// Annotation provenance:
//   When triples come from @-annotations in source code rather than from
//   a YAML file, the response carries a CodeAnchor: file path + symbol
//   (if function-scoped) + line range. This is what makes "where is this
//   rule actually enforced in code" answerable.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: awareness_graph.proto

package awarenesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AwarenessGraph_Briefing_FullMethodName                          = "/globular.awareness_graph.AwarenessGraph/Briefing"
	AwarenessGraph_Impact_FullMethodName                            = "/globular.awareness_graph.AwarenessGraph/Impact"
	AwarenessGraph_Query_FullMethodName                             = "/globular.awareness_graph.AwarenessGraph/Query"
	AwarenessGraph_Resolve_FullMethodName                           = "/globular.awareness_graph.AwarenessGraph/Resolve"
	AwarenessGraph_Metadata_FullMethodName                          = "/globular.awareness_graph.AwarenessGraph/Metadata"
	AwarenessGraph_Preflight_FullMethodName                         = "/globular.awareness_graph.AwarenessGraph/Preflight"
	AwarenessGraph_EditCheck_FullMethodName                         = "/globular.awareness_graph.AwarenessGraph/EditCheck"
	AwarenessGraph_Propose_FullMethodName                           = "/globular.awareness_graph.AwarenessGraph/Propose"
	AwarenessGraph_ReferenceSites_FullMethodName                    = "/globular.awareness_graph.AwarenessGraph/ReferenceSites"
	AwarenessGraph_GetArchitectureControlSnapshot_FullMethodName    = "/globular.awareness_graph.AwarenessGraph/GetArchitectureControlSnapshot"
	AwarenessGraph_ListArchitectureArtifacts_FullMethodName         = "/globular.awareness_graph.AwarenessGraph/ListArchitectureArtifacts"
	AwarenessGraph_GetArchitectureArtifactState_FullMethodName      = "/globular.awareness_graph.AwarenessGraph/GetArchitectureArtifactState"
	AwarenessGraph_GetOntologyNavigationDescriptor_FullMethodName   = "/globular.awareness_graph.AwarenessGraph/GetOntologyNavigationDescriptor"
	AwarenessGraph_PrepareArchitectAnswerDisposition_FullMethodName = "/globular.awareness_graph.AwarenessGraph/PrepareArchitectAnswerDisposition"
	AwarenessGraph_RecordArchitectAnswerDisposition_FullMethodName  = "/globular.awareness_graph.AwarenessGraph/RecordArchitectAnswerDisposition"
	AwarenessGraph_PromoteArchitectAnswer_FullMethodName            = "/globular.awareness_graph.AwarenessGraph/PromoteArchitectAnswer"
)

// AwarenessGraphClient is the client API for AwarenessGraph service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AwarenessGraphClient interface {
	// Briefing composes a ~500-token prose briefing for editing a file or
	// tackling a task. The single entry point agents should call before
	// significant code changes. Composed from the same SPARQL queries that
	// back Impact; the difference is presentation, not data.
	Briefing(ctx context.Context, in *BriefingRequest, opts ...grpc.CallOption) (*BriefingResponse, error)
	// Impact returns the structured data the Briefing composer uses. Direct
	// (file is the explicit subject of the node) vs Inferred (reached via
	// package/symbol walks) partition matches the existing services-repo
	// analysis package contract.
	Impact(ctx context.Context, in *ImpactRequest, opts ...grpc.CallOption) (*ImpactResponse, error)
	// Query exposes constrained typed graph browsing only. ArchitectureClaim,
	// OpenQuestion, and ArchitectAnswer are available here only when explicitly
	// requested; they remain non-authoritative and are not surfaced through
	// Briefing, Impact, or Preflight.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Resolve fetches a single node by its annotation ID (e.g. "invariant:foo",
	// "pat.bar"). Returns the node's triples plus any code-anchor provenance.
	// This is the tool agents call after reading a // @invariant: X comment, or
	// when explicitly inspecting a non-authoritative architecture_claim,
	// open_question, or architect_answer.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// Metadata returns coverage and freshness signals about the graph itself
	// — not about any specific file. Agents call this at session start so
	// they can tell whether an EMPTY briefing means "no rules apply here"
	// (graph is well-covered) vs "this area is unannotated" (graph coverage
	// is thin in this domain).
	//
	// Cheap: counts are computed live via SPARQL but the queries are bounded
	// and small. Safe to call once per session or per task.
	Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Preflight is the agent's pre-edit decision-support call. Given a task
	// and optional file list, it returns a single risk_class the agent can
	// branch on, plus required_actions, forbidden_fixes, tests_to_run, and
	// files_to_read assembled from anchored graph facts (never invented).
	//
	// Reuses Briefing's matching engine; adds risk classification, coverage
	// discipline, and action-oriented response shape on top. EMPTY does NOT
	// become LOW_RISK unless coverage explicitly says coverage is
	// sufficient — if the graph doesn't know the area, the response is
	// UNKNOWN_IMPACT and the agent is told to proceed carefully.
	//
	// Store unavailable degrades to PREFLIGHT_STATUS_DEGRADED with
	// UNKNOWN_IMPACT and blind_spots="awareness_store_unavailable" rather
	// than hard-failing. Only returns codes.Unavailable if the handler
	// cannot construct any response at all.
	Preflight(ctx context.Context, in *PreflightRequest, opts ...grpc.CallOption) (*PreflightResponse, error)
	// EditCheck evaluates a proposed edit's content against the active
	// repo-scoped advisory rules ("detect" blocks) that apply to the file, in
	// the caller's resolved domain. It is WARNING-ONLY: it never blocks, never
	// modifies code, and returns warnings naming the rule a bad-shape edit
	// would violate (e.g. replacing dispenser.Errf with fmt.Errorf in a Caddy
	// Caddyfile unmarshaler). Domain scoping is identical to Briefing/Impact:
	// a multi-domain graph with no domain fails closed; cross-domain rules
	// never apply. See golang/server/scope.go.
	EditCheck(ctx context.Context, in *EditCheckRequest, opts ...grpc.CallOption) (*EditCheckResponse, error)
	// Propose submits a typed feedback entry (failure_mode, invariant,
	// required_test, forbidden_fix, or contract_unknown) to the awareness
	// corpus's review queue. It is the agent write path: an agent that learned
	// something durable proposes it here.
	//
	// The entry is validated with the SAME contract-first rules as `awg propose`
	// and written as a candidate under docs/awareness/candidates/proposals/ — it
	// is NOT a live graph node and does NOT trigger a rebuild. Promotion into the
	// canonical corpus stays a human/CI-gated step, so the served graph never
	// silently mutates durable truth (preserving the CLI-not-durable-mutation
	// contract; the RPC only queues a proposal). Requires the server to be
	// configured with a candidates directory; returns Unavailable otherwise.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// ReferenceSites returns, for each requested code-symbol id, the set of
	// OTHER code symbols that reference it (inbound aw:references edges from
	// ingested SCIP occurrences). This is the completeness primitive: given the
	// symbols a change touches, it answers "N sites share this reference; which
	// ones did the diff miss?". Directed and complete — it reads inbound edges
	// straight from the store, so a target with many OUTGOING references does not
	// crowd out its referencing sites (as a bidirectional related-walk would).
	// External targets (stdlib/third-party, id "external:<name>") have no
	// in-repo definition and are ignored. Cheap: one inbound describe per id.
	ReferenceSites(ctx context.Context, in *ReferenceSitesRequest, opts ...grpc.CallOption) (*ReferenceSitesResponse, error)
	// GetArchitectureControlSnapshot returns architecture.control_snapshot/v1 —
	// the bounded repository overview (typed counts, attention, authority).
	GetArchitectureControlSnapshot(ctx context.Context, in *GetArchitectureControlSnapshotRequest, opts ...grpc.CallOption) (*GetArchitectureControlSnapshotResponse, error)
	// ListArchitectureArtifacts returns one page of architecture.artifact_index/v1.
	// The cursor is OPAQUE: produced and validated only by the controlstate
	// owner, bound to snapshot/registry/filter identity, rejected on mismatch.
	ListArchitectureArtifacts(ctx context.Context, in *ListArchitectureArtifactsRequest, opts ...grpc.CallOption) (*ListArchitectureArtifactsResponse, error)
	// GetArchitectureArtifactState returns architecture.artifact_state/v1 for ONE
	// exact node IRI. The canonical class is resolved by the controlstate
	// registry from observed graph classes — never supplied by the caller.
	GetArchitectureArtifactState(ctx context.Context, in *GetArchitectureArtifactStateRequest, opts ...grpc.CallOption) (*GetArchitectureArtifactStateResponse, error)
	// GetOntologyNavigationDescriptor returns ontology.navigation_descriptor/v1 —
	// registry-derived, repository-independent; requires no filesystem context.
	GetOntologyNavigationDescriptor(ctx context.Context, in *GetOntologyNavigationDescriptorRequest, opts ...grpc.CallOption) (*GetOntologyNavigationDescriptorResponse, error)
	// ── Phase 9.5 Checkpoint 5: the guarded architect-answer mutation family ──
	// The FIRST and ONLY mutation RPCs in the control-panel surface. Each is a
	// guarded delegation to an existing owner (questiondisposition /
	// questionpromotion); the server assigns no authority. A refused mutation is a
	// SUCCESSFUL response carrying a typed refusal (mirrors Propose REJECTED),
	// never a transport error. Requests carry LOGICAL identities + an actor
	// identity only — filesystem roots come from the startup-owned context.
	PrepareArchitectAnswerDisposition(ctx context.Context, in *PrepareArchitectAnswerDispositionRequest, opts ...grpc.CallOption) (*PrepareArchitectAnswerDispositionResponse, error)
	RecordArchitectAnswerDisposition(ctx context.Context, in *RecordArchitectAnswerDispositionRequest, opts ...grpc.CallOption) (*RecordArchitectAnswerDispositionResponse, error)
	PromoteArchitectAnswer(ctx context.Context, in *PromoteArchitectAnswerRequest, opts ...grpc.CallOption) (*PromoteArchitectAnswerResponse, error)
}

type awarenessGraphClient struct {
	cc grpc.ClientConnInterface
}

func NewAwarenessGraphClient(cc grpc.ClientConnInterface) AwarenessGraphClient {
	return &awarenessGraphClient{cc}
}

func (c *awarenessGraphClient) Briefing(ctx context.Context, in *BriefingRequest, opts ...grpc.CallOption) (*BriefingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BriefingResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Briefing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Impact(ctx context.Context, in *ImpactRequest, opts ...grpc.CallOption) (*ImpactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpactResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Impact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Preflight(ctx context.Context, in *PreflightRequest, opts ...grpc.CallOption) (*PreflightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreflightResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Preflight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) EditCheck(ctx context.Context, in *EditCheckRequest, opts ...grpc.CallOption) (*EditCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditCheckResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_EditCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) ReferenceSites(ctx context.Context, in *ReferenceSitesRequest, opts ...grpc.CallOption) (*ReferenceSitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReferenceSitesResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_ReferenceSites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) GetArchitectureControlSnapshot(ctx context.Context, in *GetArchitectureControlSnapshotRequest, opts ...grpc.CallOption) (*GetArchitectureControlSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchitectureControlSnapshotResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_GetArchitectureControlSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) ListArchitectureArtifacts(ctx context.Context, in *ListArchitectureArtifactsRequest, opts ...grpc.CallOption) (*ListArchitectureArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchitectureArtifactsResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_ListArchitectureArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) GetArchitectureArtifactState(ctx context.Context, in *GetArchitectureArtifactStateRequest, opts ...grpc.CallOption) (*GetArchitectureArtifactStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchitectureArtifactStateResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_GetArchitectureArtifactState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) GetOntologyNavigationDescriptor(ctx context.Context, in *GetOntologyNavigationDescriptorRequest, opts ...grpc.CallOption) (*GetOntologyNavigationDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOntologyNavigationDescriptorResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_GetOntologyNavigationDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) PrepareArchitectAnswerDisposition(ctx context.Context, in *PrepareArchitectAnswerDispositionRequest, opts ...grpc.CallOption) (*PrepareArchitectAnswerDispositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareArchitectAnswerDispositionResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_PrepareArchitectAnswerDisposition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) RecordArchitectAnswerDisposition(ctx context.Context, in *RecordArchitectAnswerDispositionRequest, opts ...grpc.CallOption) (*RecordArchitectAnswerDispositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordArchitectAnswerDispositionResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_RecordArchitectAnswerDisposition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awarenessGraphClient) PromoteArchitectAnswer(ctx context.Context, in *PromoteArchitectAnswerRequest, opts ...grpc.CallOption) (*PromoteArchitectAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteArchitectAnswerResponse)
	err := c.cc.Invoke(ctx, AwarenessGraph_PromoteArchitectAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AwarenessGraphServer is the server API for AwarenessGraph service.
// All implementations must embed UnimplementedAwarenessGraphServer
// for forward compatibility.
type AwarenessGraphServer interface {
	// Briefing composes a ~500-token prose briefing for editing a file or
	// tackling a task. The single entry point agents should call before
	// significant code changes. Composed from the same SPARQL queries that
	// back Impact; the difference is presentation, not data.
	Briefing(context.Context, *BriefingRequest) (*BriefingResponse, error)
	// Impact returns the structured data the Briefing composer uses. Direct
	// (file is the explicit subject of the node) vs Inferred (reached via
	// package/symbol walks) partition matches the existing services-repo
	// analysis package contract.
	Impact(context.Context, *ImpactRequest) (*ImpactResponse, error)
	// Query exposes constrained typed graph browsing only. ArchitectureClaim,
	// OpenQuestion, and ArchitectAnswer are available here only when explicitly
	// requested; they remain non-authoritative and are not surfaced through
	// Briefing, Impact, or Preflight.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Resolve fetches a single node by its annotation ID (e.g. "invariant:foo",
	// "pat.bar"). Returns the node's triples plus any code-anchor provenance.
	// This is the tool agents call after reading a // @invariant: X comment, or
	// when explicitly inspecting a non-authoritative architecture_claim,
	// open_question, or architect_answer.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// Metadata returns coverage and freshness signals about the graph itself
	// — not about any specific file. Agents call this at session start so
	// they can tell whether an EMPTY briefing means "no rules apply here"
	// (graph is well-covered) vs "this area is unannotated" (graph coverage
	// is thin in this domain).
	//
	// Cheap: counts are computed live via SPARQL but the queries are bounded
	// and small. Safe to call once per session or per task.
	Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// Preflight is the agent's pre-edit decision-support call. Given a task
	// and optional file list, it returns a single risk_class the agent can
	// branch on, plus required_actions, forbidden_fixes, tests_to_run, and
	// files_to_read assembled from anchored graph facts (never invented).
	//
	// Reuses Briefing's matching engine; adds risk classification, coverage
	// discipline, and action-oriented response shape on top. EMPTY does NOT
	// become LOW_RISK unless coverage explicitly says coverage is
	// sufficient — if the graph doesn't know the area, the response is
	// UNKNOWN_IMPACT and the agent is told to proceed carefully.
	//
	// Store unavailable degrades to PREFLIGHT_STATUS_DEGRADED with
	// UNKNOWN_IMPACT and blind_spots="awareness_store_unavailable" rather
	// than hard-failing. Only returns codes.Unavailable if the handler
	// cannot construct any response at all.
	Preflight(context.Context, *PreflightRequest) (*PreflightResponse, error)
	// EditCheck evaluates a proposed edit's content against the active
	// repo-scoped advisory rules ("detect" blocks) that apply to the file, in
	// the caller's resolved domain. It is WARNING-ONLY: it never blocks, never
	// modifies code, and returns warnings naming the rule a bad-shape edit
	// would violate (e.g. replacing dispenser.Errf with fmt.Errorf in a Caddy
	// Caddyfile unmarshaler). Domain scoping is identical to Briefing/Impact:
	// a multi-domain graph with no domain fails closed; cross-domain rules
	// never apply. See golang/server/scope.go.
	EditCheck(context.Context, *EditCheckRequest) (*EditCheckResponse, error)
	// Propose submits a typed feedback entry (failure_mode, invariant,
	// required_test, forbidden_fix, or contract_unknown) to the awareness
	// corpus's review queue. It is the agent write path: an agent that learned
	// something durable proposes it here.
	//
	// The entry is validated with the SAME contract-first rules as `awg propose`
	// and written as a candidate under docs/awareness/candidates/proposals/ — it
	// is NOT a live graph node and does NOT trigger a rebuild. Promotion into the
	// canonical corpus stays a human/CI-gated step, so the served graph never
	// silently mutates durable truth (preserving the CLI-not-durable-mutation
	// contract; the RPC only queues a proposal). Requires the server to be
	// configured with a candidates directory; returns Unavailable otherwise.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// ReferenceSites returns, for each requested code-symbol id, the set of
	// OTHER code symbols that reference it (inbound aw:references edges from
	// ingested SCIP occurrences). This is the completeness primitive: given the
	// symbols a change touches, it answers "N sites share this reference; which
	// ones did the diff miss?". Directed and complete — it reads inbound edges
	// straight from the store, so a target with many OUTGOING references does not
	// crowd out its referencing sites (as a bidirectional related-walk would).
	// External targets (stdlib/third-party, id "external:<name>") have no
	// in-repo definition and are ignored. Cheap: one inbound describe per id.
	ReferenceSites(context.Context, *ReferenceSitesRequest) (*ReferenceSitesResponse, error)
	// GetArchitectureControlSnapshot returns architecture.control_snapshot/v1 —
	// the bounded repository overview (typed counts, attention, authority).
	GetArchitectureControlSnapshot(context.Context, *GetArchitectureControlSnapshotRequest) (*GetArchitectureControlSnapshotResponse, error)
	// ListArchitectureArtifacts returns one page of architecture.artifact_index/v1.
	// The cursor is OPAQUE: produced and validated only by the controlstate
	// owner, bound to snapshot/registry/filter identity, rejected on mismatch.
	ListArchitectureArtifacts(context.Context, *ListArchitectureArtifactsRequest) (*ListArchitectureArtifactsResponse, error)
	// GetArchitectureArtifactState returns architecture.artifact_state/v1 for ONE
	// exact node IRI. The canonical class is resolved by the controlstate
	// registry from observed graph classes — never supplied by the caller.
	GetArchitectureArtifactState(context.Context, *GetArchitectureArtifactStateRequest) (*GetArchitectureArtifactStateResponse, error)
	// GetOntologyNavigationDescriptor returns ontology.navigation_descriptor/v1 —
	// registry-derived, repository-independent; requires no filesystem context.
	GetOntologyNavigationDescriptor(context.Context, *GetOntologyNavigationDescriptorRequest) (*GetOntologyNavigationDescriptorResponse, error)
	// ── Phase 9.5 Checkpoint 5: the guarded architect-answer mutation family ──
	// The FIRST and ONLY mutation RPCs in the control-panel surface. Each is a
	// guarded delegation to an existing owner (questiondisposition /
	// questionpromotion); the server assigns no authority. A refused mutation is a
	// SUCCESSFUL response carrying a typed refusal (mirrors Propose REJECTED),
	// never a transport error. Requests carry LOGICAL identities + an actor
	// identity only — filesystem roots come from the startup-owned context.
	PrepareArchitectAnswerDisposition(context.Context, *PrepareArchitectAnswerDispositionRequest) (*PrepareArchitectAnswerDispositionResponse, error)
	RecordArchitectAnswerDisposition(context.Context, *RecordArchitectAnswerDispositionRequest) (*RecordArchitectAnswerDispositionResponse, error)
	PromoteArchitectAnswer(context.Context, *PromoteArchitectAnswerRequest) (*PromoteArchitectAnswerResponse, error)
	mustEmbedUnimplementedAwarenessGraphServer()
}

// UnimplementedAwarenessGraphServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAwarenessGraphServer struct{}

func (UnimplementedAwarenessGraphServer) Briefing(context.Context, *BriefingRequest) (*BriefingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Briefing not implemented")
}
func (UnimplementedAwarenessGraphServer) Impact(context.Context, *ImpactRequest) (*ImpactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Impact not implemented")
}
func (UnimplementedAwarenessGraphServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAwarenessGraphServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedAwarenessGraphServer) Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedAwarenessGraphServer) Preflight(context.Context, *PreflightRequest) (*PreflightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preflight not implemented")
}
func (UnimplementedAwarenessGraphServer) EditCheck(context.Context, *EditCheckRequest) (*EditCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditCheck not implemented")
}
func (UnimplementedAwarenessGraphServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedAwarenessGraphServer) ReferenceSites(context.Context, *ReferenceSitesRequest) (*ReferenceSitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReferenceSites not implemented")
}
func (UnimplementedAwarenessGraphServer) GetArchitectureControlSnapshot(context.Context, *GetArchitectureControlSnapshotRequest) (*GetArchitectureControlSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchitectureControlSnapshot not implemented")
}
func (UnimplementedAwarenessGraphServer) ListArchitectureArtifacts(context.Context, *ListArchitectureArtifactsRequest) (*ListArchitectureArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchitectureArtifacts not implemented")
}
func (UnimplementedAwarenessGraphServer) GetArchitectureArtifactState(context.Context, *GetArchitectureArtifactStateRequest) (*GetArchitectureArtifactStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchitectureArtifactState not implemented")
}
func (UnimplementedAwarenessGraphServer) GetOntologyNavigationDescriptor(context.Context, *GetOntologyNavigationDescriptorRequest) (*GetOntologyNavigationDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOntologyNavigationDescriptor not implemented")
}
func (UnimplementedAwarenessGraphServer) PrepareArchitectAnswerDisposition(context.Context, *PrepareArchitectAnswerDispositionRequest) (*PrepareArchitectAnswerDispositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareArchitectAnswerDisposition not implemented")
}
func (UnimplementedAwarenessGraphServer) RecordArchitectAnswerDisposition(context.Context, *RecordArchitectAnswerDispositionRequest) (*RecordArchitectAnswerDispositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordArchitectAnswerDisposition not implemented")
}
func (UnimplementedAwarenessGraphServer) PromoteArchitectAnswer(context.Context, *PromoteArchitectAnswerRequest) (*PromoteArchitectAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteArchitectAnswer not implemented")
}
func (UnimplementedAwarenessGraphServer) mustEmbedUnimplementedAwarenessGraphServer() {}
func (UnimplementedAwarenessGraphServer) testEmbeddedByValue()                        {}

// UnsafeAwarenessGraphServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AwarenessGraphServer will
// result in compilation errors.
type UnsafeAwarenessGraphServer interface {
	mustEmbedUnimplementedAwarenessGraphServer()
}

func RegisterAwarenessGraphServer(s grpc.ServiceRegistrar, srv AwarenessGraphServer) {
	// If the following call panics, it indicates UnimplementedAwarenessGraphServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AwarenessGraph_ServiceDesc, srv)
}

func _AwarenessGraph_Briefing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BriefingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Briefing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Briefing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Briefing(ctx, req.(*BriefingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Impact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Impact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Impact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Impact(ctx, req.(*ImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Metadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Preflight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreflightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Preflight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Preflight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Preflight(ctx, req.(*PreflightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_EditCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).EditCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_EditCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).EditCheck(ctx, req.(*EditCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_ReferenceSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceSitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).ReferenceSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_ReferenceSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).ReferenceSites(ctx, req.(*ReferenceSitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_GetArchitectureControlSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchitectureControlSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).GetArchitectureControlSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_GetArchitectureControlSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).GetArchitectureControlSnapshot(ctx, req.(*GetArchitectureControlSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_ListArchitectureArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchitectureArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).ListArchitectureArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_ListArchitectureArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).ListArchitectureArtifacts(ctx, req.(*ListArchitectureArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_GetArchitectureArtifactState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchitectureArtifactStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).GetArchitectureArtifactState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_GetArchitectureArtifactState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).GetArchitectureArtifactState(ctx, req.(*GetArchitectureArtifactStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_GetOntologyNavigationDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOntologyNavigationDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).GetOntologyNavigationDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_GetOntologyNavigationDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).GetOntologyNavigationDescriptor(ctx, req.(*GetOntologyNavigationDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_PrepareArchitectAnswerDisposition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareArchitectAnswerDispositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).PrepareArchitectAnswerDisposition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_PrepareArchitectAnswerDisposition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).PrepareArchitectAnswerDisposition(ctx, req.(*PrepareArchitectAnswerDispositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_RecordArchitectAnswerDisposition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordArchitectAnswerDispositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).RecordArchitectAnswerDisposition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_RecordArchitectAnswerDisposition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).RecordArchitectAnswerDisposition(ctx, req.(*RecordArchitectAnswerDispositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwarenessGraph_PromoteArchitectAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteArchitectAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwarenessGraphServer).PromoteArchitectAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwarenessGraph_PromoteArchitectAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwarenessGraphServer).PromoteArchitectAnswer(ctx, req.(*PromoteArchitectAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AwarenessGraph_ServiceDesc is the grpc.ServiceDesc for AwarenessGraph service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AwarenessGraph_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "globular.awareness_graph.AwarenessGraph",
	HandlerType: (*AwarenessGraphServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Briefing",
			Handler:    _AwarenessGraph_Briefing_Handler,
		},
		{
			MethodName: "Impact",
			Handler:    _AwarenessGraph_Impact_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AwarenessGraph_Query_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _AwarenessGraph_Resolve_Handler,
		},
		{
			MethodName: "Metadata",
			Handler:    _AwarenessGraph_Metadata_Handler,
		},
		{
			MethodName: "Preflight",
			Handler:    _AwarenessGraph_Preflight_Handler,
		},
		{
			MethodName: "EditCheck",
			Handler:    _AwarenessGraph_EditCheck_Handler,
		},
		{
			MethodName: "Propose",
			Handler:    _AwarenessGraph_Propose_Handler,
		},
		{
			MethodName: "ReferenceSites",
			Handler:    _AwarenessGraph_ReferenceSites_Handler,
		},
		{
			MethodName: "GetArchitectureControlSnapshot",
			Handler:    _AwarenessGraph_GetArchitectureControlSnapshot_Handler,
		},
		{
			MethodName: "ListArchitectureArtifacts",
			Handler:    _AwarenessGraph_ListArchitectureArtifacts_Handler,
		},
		{
			MethodName: "GetArchitectureArtifactState",
			Handler:    _AwarenessGraph_GetArchitectureArtifactState_Handler,
		},
		{
			MethodName: "GetOntologyNavigationDescriptor",
			Handler:    _AwarenessGraph_GetOntologyNavigationDescriptor_Handler,
		},
		{
			MethodName: "PrepareArchitectAnswerDisposition",
			Handler:    _AwarenessGraph_PrepareArchitectAnswerDisposition_Handler,
		},
		{
			MethodName: "RecordArchitectAnswerDisposition",
			Handler:    _AwarenessGraph_RecordArchitectAnswerDisposition_Handler,
		},
		{
			MethodName: "PromoteArchitectAnswer",
			Handler:    _AwarenessGraph_PromoteArchitectAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "awareness_graph.proto",
}
