// SPDX-License-Identifier: AGPL-3.0-only

package gosemantics

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestGoSemanticFactsIncludeExports(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Exported", "function")
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Service", "type")
}

func TestGoSemanticFactsIncludeLocalCalls(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateCallsSymbol, "fixture.Exported", "fixture.helperCall")
}

func TestGoSemanticFactsIncludeInterfaceImplementation(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateImplementsInterface, "fixture.implementation", "fixture.Service")
}

func TestGoSemanticFactsIncludeTestToProductionCalls(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateTestCallsSymbol, "fixture.TestExported", "fixture.Exported")
}

func TestGoSemanticFactsIncludeComponentDependencies(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateComponentDependsOn, "component.fixture", "component.internal.helper")
}

func TestGoSemanticFactsExcludeVendorAndGeneratedFiles(t *testing.T) {
	result := extractFixture(t)
	for _, observation := range result.Observations {
		joined := strings.Join([]string{observation.Subject, observation.Object, observation.File}, " ")
		if strings.Contains(joined, "Generated") || strings.Contains(joined, "vendor/") {
			t.Fatalf("excluded source produced observation: %+v", observation)
		}
	}
}

func TestGoSemanticFactsAreDeterministic(t *testing.T) {
	root := writeFixture(t)
	first, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("semantic extraction changed between identical runs\nfirst:  %#v\nsecond: %#v", first, second)
	}
}

func TestSemanticInputFilesRespectExcludedPathsAndRefuseEligibleSymlinks(t *testing.T) {
	root := writeFixture(t)
	target := filepath.Join(t.TempDir(), "target")
	if err := os.WriteFile(target, []byte("package ignored\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	excluded := filepath.Join(root, "nested", "node_modules", ".bin", "tool")
	if err := os.MkdirAll(filepath.Dir(excluded), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, excluded); err != nil {
		t.Fatal(err)
	}
	first, err := SemanticInputFiles(root)
	if err != nil {
		t.Fatal(err)
	}
	second, err := SemanticInputFiles(root)
	if err != nil || !reflect.DeepEqual(first, second) {
		t.Fatalf("semantic input selection is not deterministic: %v\n%v\n%v", err, first, second)
	}
	for _, name := range []string{"external.go", "go.mod", "go.sum"} {
		path := filepath.Join(root, name)
		_ = os.Remove(path)
		if err := os.Symlink(target, path); err != nil {
			t.Fatal(err)
		}
		if _, err := SemanticInputFiles(root); err == nil {
			t.Fatalf("eligible symlink %s was accepted", name)
		}
		if err := os.Remove(path); err != nil {
			t.Fatal(err)
		}
	}
}

func TestGoSemanticFactsDoNotDependOnUserBuildCachePermissions(t *testing.T) {
	root := writeFixture(t)
	readOnly := filepath.Join(t.TempDir(), "read-only-cache")
	if err := os.MkdirAll(readOnly, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Setenv("GOCACHE", readOnly)
	result, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Exported", "function")
}

func extractFixture(t *testing.T) Result {
	t.Helper()
	result, err := Extract(writeFixture(t))
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func writeFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"go.mod": "module example.com/fixture\n\ngo 1.25.0\n",
		"fixture.go": `package fixture

import "example.com/fixture/internal/helper"

type Service interface { Run() string }
type implementation struct{}
func (implementation) Run() string { return helper.Value() }

func Exported() string { return helperCall() }
func helperCall() string { return helper.Value() }
`,
		"fixture_test.go": `package fixture

import "testing"

func TestExported(t *testing.T) {
	if Exported() == "" { t.Fatal("empty") }
}
`,
		"internal/helper/helper.go": `package helper

func Value() string { return "ok" }
`,
		"generated_generated.go": `// Code generated by fixture. DO NOT EDIT.
package fixture

func Generated() string { return "generated" }
`,
		"vendor/example.com/ignored/ignored.go": `package ignored

func VendorGenerated() string { return "ignored" }
`,
	}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func assertObservation(t *testing.T, result Result, predicate, subject, object string) {
	t.Helper()
	for _, observation := range result.Observations {
		if observation.Predicate == predicate && observation.Subject == subject && observation.Object == object {
			return
		}
	}
	t.Fatalf("missing observation %s(%s, %s) in %#v", predicate, subject, object, result.Observations)
}

func TestUnresolvedBoundaryProvenanceRegression(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"go.mod": "module example.com/fixture\n\ngo 1.25.0\n",
		"fixture.go": `package fixture
type Request struct {
	UserID string ` + "`" + `json:"user_id"` + "`" + `
}
func ValidCall(req Request) {}
`,
		"generated_crossing.go": `// Code generated by fixture. DO NOT EDIT.
package fixture
func CrossingCall(req Request) {}
`,
	}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	result, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}

	// 1. Prove no crossing fact cites the declaration as fallback evidence
	for _, obs := range result.Observations {
		if obs.Predicate == "uses_data_shape_across_boundary" && obs.Object == "fixture.CrossingCall" {
			t.Errorf("Falsely emitted crossing observation with declaration as fallback: %+v", obs)
		}
	}

	// 2. Prove that a limitation is present for the unresolved crossing
	foundLimitation := false
	for _, lim := range result.Limitations {
		if lim.Scope == "fixture.Request" && strings.Contains(lim.Reason, "boundary crossing location unresolved: fixture.CrossingCall") {
			foundLimitation = true
			break
		}
	}
	if !foundLimitation {
		t.Errorf("Expected limitation identifying the unresolved crossing to be present, got: %+v", result.Limitations)
	}

	// 3. Prove that the valid crossing observation remains unchanged
	foundValid := false
	for _, obs := range result.Observations {
		if obs.Predicate == "uses_data_shape_across_boundary" && obs.Object == "fixture.ValidCall" {
			foundValid = true
			if obs.File != "fixture.go" {
				t.Errorf("Expected valid crossing file to be fixture.go, got %q", obs.File)
			}
		}
	}
	if !foundValid {
		t.Errorf("Expected valid crossing observation to be present, but was missing")
	}

	// 4. Prove that repeated runs produce identical results
	result2, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(result, result2) {
		t.Errorf("Extract is not deterministic on unresolved position regression")
	}
}
