// SPDX-License-Identifier: AGPL-3.0-only

package gosemantics

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestGoSemanticFactsIncludeExports(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Exported", "function")
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Service", "type")
}

func TestGoSemanticFactsIncludeLocalCalls(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateCallsSymbol, "fixture.Exported", "fixture.helperCall")
}

func TestGoSemanticFactsIncludeInterfaceImplementation(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateImplementsInterface, "fixture.implementation", "fixture.Service")
}

func TestGoSemanticFactsIncludeTestToProductionCalls(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateTestCallsSymbol, "fixture.TestExported", "fixture.Exported")
}

func TestGoSemanticFactsIncludeComponentDependencies(t *testing.T) {
	result := extractFixture(t)
	assertObservation(t, result, PredicateComponentDependsOn, "component.fixture", "component.internal.helper")
}

func TestGoSemanticFactsExcludeVendorAndGeneratedFiles(t *testing.T) {
	result := extractFixture(t)
	for _, observation := range result.Observations {
		joined := strings.Join([]string{observation.Subject, observation.Object, observation.File}, " ")
		if strings.Contains(joined, "Generated") || strings.Contains(joined, "vendor/") {
			t.Fatalf("excluded source produced observation: %+v", observation)
		}
	}
}

func TestGoSemanticFactsAreDeterministic(t *testing.T) {
	root := writeFixture(t)
	first, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("semantic extraction changed between identical runs\nfirst:  %#v\nsecond: %#v", first, second)
	}
}

func TestGoSemanticFactsDoNotDependOnUserBuildCachePermissions(t *testing.T) {
	root := writeFixture(t)
	readOnly := filepath.Join(t.TempDir(), "read-only-cache")
	if err := os.MkdirAll(readOnly, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Setenv("GOCACHE", readOnly)
	result, err := Extract(root)
	if err != nil {
		t.Fatal(err)
	}
	assertObservation(t, result, PredicateExportsSymbol, "fixture.Exported", "function")
}

func extractFixture(t *testing.T) Result {
	t.Helper()
	result, err := Extract(writeFixture(t))
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func writeFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"go.mod": "module example.com/fixture\n\ngo 1.25.0\n",
		"fixture.go": `package fixture

import "example.com/fixture/internal/helper"

type Service interface { Run() string }
type implementation struct{}
func (implementation) Run() string { return helper.Value() }

func Exported() string { return helperCall() }
func helperCall() string { return helper.Value() }
`,
		"fixture_test.go": `package fixture

import "testing"

func TestExported(t *testing.T) {
	if Exported() == "" { t.Fatal("empty") }
}
`,
		"internal/helper/helper.go": `package helper

func Value() string { return "ok" }
`,
		"generated_generated.go": `// Code generated by fixture. DO NOT EDIT.
package fixture

func Generated() string { return "generated" }
`,
		"vendor/example.com/ignored/ignored.go": `package ignored

func VendorGenerated() string { return "ignored" }
`,
	}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func assertObservation(t *testing.T, result Result, predicate, subject, object string) {
	t.Helper()
	for _, observation := range result.Observations {
		if observation.Predicate == predicate && observation.Subject == subject && observation.Object == object {
			return
		}
	}
	t.Fatalf("missing observation %s(%s, %s) in %#v", predicate, subject, object, result.Observations)
}
