// SPDX-License-Identifier: Apache-2.0

// Command awareness-graph is the gRPC service entry point.
//
// Scope (Phase 2 step 7):
//
//   - Flags: -addr (gRPC listen address), -oxigraph-url (SPARQL query
//     endpoint), -require-store (fail-fast on backend health failure).
//   - Construct an Oxigraph client at startup.
//   - Run a one-shot health check; honor -require-store for whether a
//     failure is fatal.
//   - Build the gRPC server with the store reference held on the
//     concrete server struct so future RPC implementations can reach it.
//   - Register the AwarenessGraphServer with Resolve + Impact + Briefing + Query implemented.
//   - Graceful shutdown on SIGINT/SIGTERM; Close() the store last so
//     queries in flight aren't yanked from under their handlers.
//
// Out of scope (deliberately deferred):
//
//   - Arbitrary SPARQL passthrough.
//
//   - Periodic re-checks / readiness probes. One health check at
//     startup, no background loop. Re-checks land if a future operator
//     surface demands them.
package main

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	_ "embed"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"

	"github.com/globulario/sensei/golang/netcfg"
	awarenesspb "github.com/globulario/sensei/golang/pb"
	"github.com/globulario/sensei/golang/seedmeta"
	"github.com/globulario/sensei/golang/store"
	"github.com/globulario/sensei/golang/store/oxigraph"
)

// seedNT is the compiled awareness knowledge graph embedded at build time.
// It is generated by yaml2nt from docs/awareness and docs/intent YAML sources.
// On a fresh Oxigraph store (zero triples), the server loads this seed so
// the service is immediately queryable without a separate data-load step.
//
//go:embed embeddata/awareness.nt
var seedNT []byte

// seedTransactionStamp is the committed cross-repo certification stamp for
// the embedded seed. It must describe the same seed digest as seedNT before
// runtime metadata can present the transaction as authoritative.
//
//go:embed embeddata/awareness.transaction.tsv
var seedTransactionStamp []byte

// Version is set at build time via -X main.Version=<ver>. "0.0.0-dev"
// is the sentinel for an un-ldflag-ed build.
var Version = "0.0.0-dev"

func authTokenFromEnv() string {
	if v := strings.TrimSpace(os.Getenv("SENSEI_TOKEN")); v != "" {
		return v
	}
	return strings.TrimSpace(os.Getenv("AWG_TOKEN"))
}

// Build-time provenance stamps. Set via ldflags:
//
//	-X main.BuildCommit=<awareness-graph SHA>
//	-X main.SourceCommit=<services repo SHA>
//	-X main.BuildTimeUnix=<unix seconds>
//
// Empty / zero values are valid and reported as-is — agents disambiguate
// "stamped but old" from "never stamped" by checking for empty.
var (
	BuildCommit   = ""
	SourceCommit  = ""
	BuildTimeUnix = "" // numeric string; parsed at first use
)

// serverStartedUnix records the wall-clock time the server process started.
// Used by Metadata to expose process uptime. Set in main() before any RPC
// can be served so the response value is always meaningful.
var serverStartedUnix int64

// startupHealthTimeout caps the one-shot backend check at startup.
// Long enough to tolerate a cold-started Oxigraph; short enough that a
// genuinely dead backend doesn't delay -require-store=true exits.
const startupHealthTimeout = 5 * time.Second

// server is the concrete gRPC implementation of AwarenessGraphServer.
//
// The Store reference is held but currently unused. When Resolve and
// the other RPCs land, they will reach into s.store for their SPARQL
// calls. Holding the reference now means the wiring is committed to,
// reviewable, and tested before the first real RPC introduces query
// shape decisions.
//
// Embedding UnimplementedAwarenessGraphServer keeps any future-added RPCs
// returning codes.Unimplemented by default.
type server struct {
	awarenesspb.UnimplementedAwarenessGraphServer
	store  store.Store // nil-safe; future RPCs check before use
	logger *log.Logger

	// homeDomain is the domain key for the host project's own (untagged)
	// knowledge nodes — those authored before domain tagging, with no aw:repo /
	// aw:domain fact. They behave as one domain so a single-domain graph keeps
	// resolving trivially and a mixed graph (home + a foreign repo) correctly
	// detects 2 domains and fails closed on an unscoped query. Configurable via
	// `awg serve --home-domain`; defaults to defaultHomeDomain.
	homeDomain string

	// Cached meta-principles for principle-based briefing reasoning.
	metaPrincipleOnce sync.Once
	metaPrinciples    []principleMatch
	surfaceUsage      surfaceUsageCounters
	graphMarkerFile   string

	// awarenessDir is the source docs/awareness directory. When set, the Propose
	// RPC writes agent-submitted candidates under <awarenessDir>/candidates/.
	// Empty disables the write path (Propose returns Unavailable) — the default,
	// so a read-only served graph never gains a write surface by accident.
	awarenessDir string
}

// defaultHomeDomain is the domain key assigned to untagged host-project nodes
// when no --home-domain is configured. The production host is Globular.
const defaultHomeDomain = "globular"

func newServer(s store.Store) *server {
	return &server{
		store:      s,
		logger:     log.New(io.Discard, "", 0),
		homeDomain: defaultHomeDomain,
	}
}

func main() {
	serverStartedUnix = time.Now().Unix()
	cfgPath := flag.String("config", "", "optional path to service config JSON")
	id := flag.String("id", "", "optional service instance id")
	addr := flag.String("addr", "", "TCP address to listen on (standalone mode)")
	oxigraphURL := flag.String("oxigraph-url", "",
		"Oxigraph SPARQL query endpoint")
	noSeed := flag.Bool("no-seed", false,
		"skip seeding the embedded Globular awareness.nt into an empty store — "+
			"cold-start projects build their own graph with `awg build`")
	allowStaleSeed := flag.Bool("allow-stale-seed", false,
		"allow startup when the live store does not contain this binary's embedded seed marker; "+
			"default is fail-closed for embedded-seed deployments")
	graphMarkerFile := flag.String("graph-marker-file", "", "runtime graph marker file for -no-seed deployments")
	awarenessDir := flag.String("awareness-dir", "",
		"source docs/awareness directory; enables the Propose RPC to write agent candidates under it (empty = write path disabled)")
	requireStore := flag.Bool("require-store", false,
		"if true, exit non-zero when the RDF backend is unhealthy at startup")
	homeDomain := flag.String("home-domain", defaultHomeDomain,
		"domain key for the host project's own untagged knowledge nodes; "+
			"cold-start non-Globular deployments should set this to their project key")
	authToken := flag.String("auth-token", authTokenFromEnv(),
		"require this bearer token on every AwarenessGraph RPC (health/reflection exempt). Default: $SENSEI_TOKEN, then legacy $AWG_TOKEN. Empty = open (trusted-network self-host default).")
	debug := flag.Bool("debug", false, "enable verbose startup logs")
	describeFlag := flag.Bool("describe", false, "print service description as JSON and exit")
	healthFlag := flag.Bool("health", false, "print service health as JSON and exit")
	versionFlag := flag.Bool("version", false, "print version and exit")
	preflightFlag := flag.Bool("preflight", false, "run one offline Preflight against the EMBEDDED seed (no Oxigraph, no cluster) and exit")
	preflightTask := flag.String("task", "", "task text for -preflight")
	var preflightFiles stringListFlag
	flag.Var(&preflightFiles, "file", "repo-relative file for -preflight (repeatable)")
	preflightMode := flag.String("mode", "standard", "-preflight mode: standard | compact")
	preflightJSON := flag.Bool("json", false, "emit -preflight result as JSON")
	flag.Parse()

	if *versionFlag {
		fmt.Println(Version)
		return
	}
	if *preflightFlag {
		if *preflightTask == "" && len(preflightFiles) == 0 {
			fmt.Fprintln(os.Stderr, "awareness-graph -preflight: provide -task and/or -file")
			os.Exit(2)
		}
		os.Exit(runPreflightCLI(os.Stdout, *preflightTask, preflightFiles, *preflightMode, *preflightJSON))
	}
	cfg, err := loadServiceConfig(*cfgPath)
	if err != nil {
		log.Fatalf("awareness-graph: load config: %v", err)
	}
	if *id != "" {
		cfg.ID = *id
	}
	if *oxigraphURL != "" {
		cfg.OxigraphQueryURL = *oxigraphURL
	}
	if *debug {
		log.Printf("awareness-graph: debug enabled")
	}
	if *describeFlag {
		if err := printDescribeJSON(os.Stdout, cfg); err != nil {
			log.Fatalf("awareness-graph: --describe: %v", err)
		}
		return
	}
	if *healthFlag {
		os.Exit(printHealthJSON(os.Stdout, cfg))
	}

	// Sensei runs as a standalone sidecar, not a Globular-registered service:
	// the listen address comes from -addr, else $SENSEI_ADDR (legacy $AWG_ADDR),
	// else :10120. There is no etcd service-registry authority to consult.
	finalAddr := *addr
	if finalAddr == "" {
		finalAddr = netcfg.ServiceListenAddr()
	}
	finalRequireStore := *requireStore || cfg.RequireStore

	markerFile := strings.TrimSpace(*graphMarkerFile)
	if *noSeed && markerFile == "" {
		// Relative to the working directory; RuntimeMarkerPath honors an
		// existing legacy .awg/ store, otherwise defaults to .sensei/.
		markerFile = seedmeta.RuntimeMarkerPath(".")
	}
	if err := serve(finalAddr, cfg, finalRequireStore, *noSeed, *allowStaleSeed, strings.TrimSpace(*homeDomain), markerFile, strings.TrimSpace(*awarenessDir), strings.TrimSpace(*authToken), log.Default()); err != nil {
		log.Fatalf("awareness-graph: %v", err)
	}
}

// serve drives the full lifecycle. Extracted from main() so its
// behaviour is testable (modulo the actual TCP listen and signal wait).
//
// The logger parameter exists so tests can capture log output without
// fighting the global log package. Production code passes log.Default().
func serve(addr string, cfg serviceConfig, requireStore, noSeed, allowStaleSeed bool, homeDomain, graphMarkerFile, awarenessDir, authToken string, logger *log.Logger) error {
	// 1. Construct the store. URL-level validation runs here so a
	// typo'd flag fails before TCP binds.
	rdfStore, err := oxigraph.New(cfg.OxigraphQueryURL)
	if err != nil {
		return fmt.Errorf("init store: %w", err)
	}
	defer func() {
		if cerr := rdfStore.Close(); cerr != nil {
			logger.Printf("awareness-graph: store close: %v", cerr)
		}
	}()

	// 2. Health-check the backend. -require-store decides whether a
	// failure is fatal. Centralised in validateBackend so the policy
	// is testable without binding TCP or running a real Oxigraph.
	healthCtx, cancel := context.WithTimeout(context.Background(), startupHealthTimeout)
	if err := validateBackend(healthCtx, rdfStore, requireStore, cfg.OxigraphQueryURL, logger); err != nil {
		cancel()
		return err
	}
	cancel()

	// 2b. Seed the store on a fresh install. If the default graph is empty
	// (zero triples), load the embedded awareness.nt produced at build time
	// by yaml2nt. This makes the service immediately queryable after install
	// without a separate data-load step. On a populated store the seed is
	// skipped so live data is never overwritten on restart.
	if noSeed {
		logger.Printf("awareness-graph: -no-seed — embedded seed skipped; populate the store with `awg build`")
	} else {
		seedCtx, seedCancel := context.WithTimeout(context.Background(), 90*time.Second)
		if err := seedIfEmpty(seedCtx, rdfStore, logger); err != nil {
			logger.Printf("awareness-graph: seed load failed (non-fatal): %v", err)
		}
		seedCancel()

		enforceCtx, enforceCancel := context.WithTimeout(context.Background(), 15*time.Second)
		if err := enforceCurrentSeed(enforceCtx, rdfStore, cfg.OxigraphQueryURL, allowStaleSeed, logger); err != nil {
			enforceCancel()
			return err
		}
		enforceCancel()
	}

	// 3. Bind and serve. Sensei is a local sidecar — there is no etcd
	// registration or xDS/Envoy route to publish.
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("listen on %s: %w", addr, err)
	}

	// Load cluster TLS credentials. If the cert files are absent (e.g. dev
	// machine without a Globular install) fall back to plaintext and update
	// cfg.TLS so runtime metadata reflects reality.
	var grpcOpts []grpc.ServerOption
	creds, tlsErr := buildServerTLS()
	if tlsErr != nil {
		logger.Printf("awareness-graph: TLS unavailable (%v) — serving plaintext", tlsErr)
		cfg.TLS = false
	} else {
		grpcOpts = append(grpcOpts, grpc.Creds(creds))
		cfg.TLS = true
		logger.Printf("awareness-graph: TLS enabled (cluster cert loaded)")
	}

	// Opt-in bearer-token auth. When set, every AwarenessGraph RPC must present
	// the token (health/reflection stay open for probes/tooling).
	if authToken != "" {
		grpcOpts = append(grpcOpts,
			grpc.ChainUnaryInterceptor(bearerUnaryInterceptor(authToken)),
			grpc.ChainStreamInterceptor(bearerStreamInterceptor(authToken)),
		)
		logger.Printf("awareness-graph: bearer-token auth ENABLED (health/reflection exempt)")
	}

	grpcServer := grpc.NewServer(grpcOpts...)
	srv := newServer(rdfStore)
	if homeDomain != "" {
		srv.homeDomain = homeDomain
	}
	if graphMarkerFile != "" {
		if filepath.IsAbs(graphMarkerFile) {
			srv.graphMarkerFile = graphMarkerFile
		} else {
			srv.graphMarkerFile = filepath.Clean(graphMarkerFile)
		}
	}
	if awarenessDir != "" {
		if abs, err := filepath.Abs(awarenessDir); err == nil {
			srv.awarenessDir = abs
		} else {
			srv.awarenessDir = filepath.Clean(awarenessDir)
		}
	}
	srv.logger = logger
	healthSrv := setupGrpcService(grpcServer, srv)
	monitorCtx, monitorCancel := context.WithCancel(context.Background())
	defer monitorCancel()
	go monitorBackendHealth(monitorCtx, healthSrv, rdfStore, cfg.OxigraphQueryURL, logger, backendHealthPollInterval)

	logger.Printf("awareness-graph %s listening on %s", Version, listener.Addr())
	logger.Printf("  Resolve, Impact, Briefing, and constrained Query are enabled")

	errCh := make(chan error, 1)
	go func() {
		errCh <- grpcServer.Serve(listener)
	}()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(sigCh)

	select {
	case sig := <-sigCh:
		logger.Printf("awareness-graph: received %s, starting graceful shutdown", sig)
		monitorCancel()
		grpcServer.GracefulStop()
		logger.Printf("awareness-graph: shutdown complete")
		return nil
	case err := <-errCh:
		monitorCancel()
		if err != nil {
			return fmt.Errorf("grpc serve: %w", err)
		}
		return nil
	}
}

// Standard Globular PKI paths. When present, the server serves TLS with these
// cluster credentials; when absent it falls back to plaintext (see serve). This
// is the only remaining Globular integration point — optional and fail-open.
const (
	clusterCAPath   = "/var/lib/globular/pki/ca.crt"
	clusterCertPath = "/var/lib/globular/pki/issued/services/service.crt"
	clusterKeyPath  = "/var/lib/globular/pki/issued/services/service.key"
)

// buildServerTLS loads the cluster service cert and CA from the standard
// Globular PKI paths and returns TLS server credentials. Returns an error if
// the cert files are absent so the caller can fall back to plaintext.
func buildServerTLS() (credentials.TransportCredentials, error) {
	cert, err := tls.LoadX509KeyPair(clusterCertPath, clusterKeyPath)
	if err != nil {
		return nil, fmt.Errorf("load service cert: %w", err)
	}
	caData, err := os.ReadFile(clusterCAPath)
	if err != nil {
		return nil, fmt.Errorf("read cluster CA: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caData) {
		return nil, fmt.Errorf("parse cluster CA %s", clusterCAPath)
	}
	return credentials.NewTLS(&tls.Config{
		Certificates: []tls.Certificate{cert},
		ClientCAs:    pool,
		ClientAuth:   tls.VerifyClientCertIfGiven,
		MinVersion:   tls.VersionTLS12,
	}), nil
}

// validateBackend runs Health on s and applies the -require-store policy.
//
//   - If Health succeeds: log "backend healthy at <url>" and return nil.
//   - If Health fails AND requireStore: return a wrapped error so the
//     caller (serve) can propagate to main()'s fatal exit.
//   - If Health fails AND !requireStore: log a clear warning and return
//     nil; the server starts and answers RPCs (still all Unimplemented
//     in this phase, so the backend being down does not yet affect
//     correctness).
//
// The endpoint URL is included in log lines so a misconfigured -oxigraph-url
// is obvious in stderr without re-grepping the invocation.
func validateBackend(ctx context.Context, s store.Store, requireStore bool, endpoint string, logger *log.Logger) error {
	if err := s.Health(ctx); err != nil {
		if requireStore {
			return fmt.Errorf("backend health check failed at %s (-require-store): %w", endpoint, err)
		}
		logger.Printf("awareness-graph: WARNING — backend unhealthy at %s: %v", endpoint, err)
		logger.Printf("awareness-graph: continuing anyway (set -require-store to fail fast)")
		return nil
	}
	logger.Printf("awareness-graph: backend healthy at %s", endpoint)
	return nil
}

// seedIfEmpty loads the embedded awareness.nt into the Oxigraph store when
// the default graph is empty. It is idempotent: a store that already has
// triples is left untouched so a restart never overwrites live data.
//
// Errors are surfaced to the caller which logs them as non-fatal — the
// service starts regardless and the store can be loaded manually later.
func seedIfEmpty(ctx context.Context, s store.Store, logger *log.Logger) error {
	// CountTriples and Load are only available on the concrete Oxigraph
	// client — they are not part of store.Store. Use interface assertions
	// so a test fake that doesn't implement them simply skips the seed.
	type counter interface {
		CountTriples(context.Context) (int64, error)
	}
	type loader interface {
		Load(context.Context, io.Reader) error
	}
	ldr, ok := s.(loader)
	if !ok {
		return nil // non-Oxigraph backend — skip
	}

	cnt, ok := s.(counter)
	if !ok {
		return nil // non-Oxigraph backend — skip
	}
	n, err := cnt.CountTriples(ctx)
	if err != nil {
		return fmt.Errorf("count triples: %w", err)
	}
	if n > 0 {
		logger.Printf("awareness-graph: store has %d triples — skipping seed load", n)
		return nil
	}

	seedBytes := normalizedEmbeddedSeed()
	logger.Printf("awareness-graph: store is empty — loading %d-byte seed (compiled awareness.nt)", len(seedBytes))
	if err := ldr.Load(ctx, bytes.NewReader(seedBytes)); err != nil {
		return fmt.Errorf("seed load: %w", err)
	}
	logger.Printf("awareness-graph: seed loaded successfully")
	return nil
}

func enforceCurrentSeed(ctx context.Context, s store.Store, endpoint string, allowStaleSeed bool, logger *log.Logger) error {
	verifier, ok := s.(interface {
		Describe(context.Context, string) ([]store.Triple, error)
		CountTriples(context.Context) (int64, error)
		CountByClass(context.Context, string) (int64, error)
	})
	if !ok {
		if allowStaleSeed {
			logger.Printf("awareness-graph: WARNING — store backend cannot verify graph freshness")
			logger.Printf("awareness-graph: continuing anyway (-allow-stale-seed)")
			return nil
		}
		return fmt.Errorf("store backend cannot verify graph freshness; restart with -allow-stale-seed only if you accept non-authoritative mode")
	}
	marker, ok := normalizedEmbeddedSeedMarker()
	if !ok {
		if allowStaleSeed {
			logger.Printf("awareness-graph: WARNING — embedded seed carries no marker; cannot verify live freshness")
			logger.Printf("awareness-graph: continuing anyway (-allow-stale-seed)")
			return nil
		}
		return fmt.Errorf("embedded seed carries no marker; rebuild awareness.nt and restart, or set -allow-stale-seed")
	}
	verification := seedmeta.VerifyLiveStore(ctx, verifier, marker)
	if verification.State == seedmeta.FreshnessCurrent {
		logger.Printf("awareness-graph: verified live graph authority (%s)", graphFreshnessSummary(verification))
		return nil
	}
	if allowStaleSeed {
		logger.Printf("awareness-graph: WARNING — %s", graphFreshnessSummary(verification))
		logger.Printf("awareness-graph: continuing anyway (-allow-stale-seed)")
		return nil
	}
	switch verification.State {
	case seedmeta.FreshnessCheckError:
		return fmt.Errorf("verify live graph authority at %s: %s", endpoint, verification.Detail)
	case seedmeta.FreshnessEmpty:
		return fmt.Errorf("live store at %s is empty; load a validated graph artifact or restart with -allow-stale-seed", endpoint)
	case seedmeta.FreshnessStale, seedmeta.FreshnessUnknown:
		return fmt.Errorf("live store at %s is not authoritative: %s; run `awg rebuild` or restart with -allow-stale-seed", endpoint, verification.Detail)
	default:
		if allowStaleSeed {
			logger.Printf("awareness-graph: WARNING — live graph freshness unspecified")
			logger.Printf("awareness-graph: continuing anyway (-allow-stale-seed)")
			return nil
		}
		return fmt.Errorf("live store at %s has unspecified freshness state", endpoint)
	}
}
