#!/usr/bin/env python3
"""sync-principle-pack.py — regenerate the portable principle pack from the
canonical corpus.

ONE source of truth: docs/awareness/generic/state_authority_invariants.yaml
IN THIS REPO (the corpus moved here from the services repo 2026-06-13 so the
generic knowledge is portable). This script derives ONE artifact from it:

  - cmd/awg/templates/awareness/meta_principles.yaml
    — meta.* principles only, project anchors stripped; what `sensei init`
      installs into new projects.

The generic corpus is no longer a sync OUTPUT — it IS the hand-authored
source. (--services is kept as a no-op flag for backward-compatible CI calls.)

Genericization rules, per entry:
  - drop protects: (Globular file/symbol anchors)
  - drop forbidden_fixes / required_tests / related_failure_modes /
    related_principles / related_services (project-specific knowledge)
  - related_invariants: keep only meta.* cross-links (pack-internal)
  - keep verbatim: id, title, category, antipattern, wrong_instinct,
    severity, status, summary, enforcement, and all comments (origin
    annotations, category banners)

Run: python3 scripts/sync-principle-pack.py [--services <path>] [--check]
--check: exit 1 if outputs would change (CI drift gate).
"""
import argparse, re, sys, pathlib

DROP_KEYS = ("protects", "forbidden_fixes", "required_tests",
             "related_failure_modes", "related_principles", "related_services")

def split_entries(text):
    """Split the invariants file into (preamble, [entry blocks]).
    Trailing comment banners at the end of a block belong to the NEXT block."""
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if l.startswith("  - id: ")]
    if not starts:
        sys.exit("no entries found")
    pre = lines[:starts[0]]
    blocks = []
    for n, s in enumerate(starts):
        e = starts[n + 1] if n + 1 < len(starts) else len(lines)
        blocks.append(lines[s:e])
    # move trailing comment/blank runs to the following block's head
    for n in range(len(blocks) - 1):
        blk = blocks[n]
        i = len(blk)
        while i > 0 and (not blk[i - 1].strip() or blk[i - 1].lstrip().startswith("#")):
            i -= 1
        blocks[n + 1] = blk[i:] + blocks[n + 1]
        blocks[n] = blk[:i]
    return pre, blocks

def entry_id(block):
    return block[0].split("id:", 1)[1].strip()

def genericize(block):
    """Apply the drop/filter rules to one entry block (list of lines)."""
    out, i = [], 0
    while i < len(block):
        line = block[i]
        m = re.match(r"^(\s{4})([a-z_]+):", line)
        key = m.group(2) if m else None
        if key in DROP_KEYS:
            i += 1
            while i < len(block) and (not block[i].strip()
                                      or block[i].startswith("      ")
                                      or block[i].startswith("    - ")):
                # consume the nested block (deeper indentation or list items)
                if block[i].strip() and not block[i].startswith("     ") and not block[i].startswith("    - "):
                    break
                i += 1
            continue
        if key == "related_invariants":
            items, j = [], i + 1
            while j < len(block) and re.match(r"^\s{6}- ", block[j]):
                val = block[j].split("- ", 1)[1].strip()
                if val.startswith("meta."):
                    items.append(block[j])
                j += 1
            if items:
                out.append(line)
                out.extend(items)
            i = j
            continue
        out.append(line)
        i += 1
    # trim trailing blanks
    while out and not out[-1].strip():
        out.pop()
    return out

GENERIC_HEADER = """\
# State authority invariants — generic knowledge for any software system
#
# GENERATED by scripts/sync-principle-pack.py from the canonical corpus in
# this repo (docs/awareness/generic/state_authority_invariants.yaml).
# Do not edit by hand — edit the canonical corpus and re-run the sync.
#
# Eight categories: authority, signal, lifecycle, dependency (backend truth),
# perception (does the screen tell the truth), composition (does the layout
# make truth perceivable), structure (is the code shaped to last), evolution
# (how is the project allowed to change safely over time).
#
# Project-specific anchors (protects, forbidden_fixes, required_tests,
# related_failure_modes) are stripped — add your own as your incidents
# accumulate. Summaries and prediction records (first_predicted_bug) keep
# Globular references as provenance: these principles were validated in
# production — and several predicted real bugs — not deduced in the abstract.

invariants:
"""

PACK_HEADER = """\
# Meta-Principles — generative patterns that predict where bugs hide.
#
# GENERATED by scripts/sync-principle-pack.py — do not edit by hand.
# Source of truth: docs/awareness/generic/state_authority_invariants.yaml.
# Installed into new projects by `sensei init`. Domain-independent: validated
# on the Globular platform, applicable to any operator-grade system.
#
# Eight categories:
#   authority/signal/lifecycle/dependency — backend truth handling
#   perception  — "is the screen telling the truth about the system?"
#   composition — "does the layout make truth easy to perceive?"
#   structure   — "is this unit shaped to be reused, inspected, outlive fashion?"
#   evolution   — "how is this project allowed to change safely over time?"
#
# Use them three ways: classify incidents (which principle did this violate),
# find siblings (the principle predicts where the same bug class hides), and
# brief before edits (awareness_briefing surfaces them by file role/task).
# Prediction records (first_predicted_bug) keep Globular references as
# provenance — several principles found real bugs before they fired.

invariants:
"""

def render(header, blocks):
    body = "\n\n".join("\n".join(b).rstrip() for b in blocks)
    return header + "\n" + body + "\n"

def main():
    ap = argparse.ArgumentParser()
    # --services is retained for backward compatibility / CI invocation but is
    # no longer the corpus source: the canonical corpus moved INTO this repo
    # (docs/awareness/generic/state_authority_invariants.yaml) on 2026-06-13.
    ap.add_argument("--services", default="../services",
                    help="(deprecated; ignored — corpus is now AG-internal)")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = pathlib.Path(__file__).resolve().parent.parent
    # SOURCE is the authored corpus in THIS repo. sync only derives the
    # cold-start pack from it now — the generic corpus is no longer a sync
    # output (it IS the source), which removes the old circular generate-the-
    # source problem and the double-import it caused in the seed.
    src_file = root / "docs/awareness/generic/state_authority_invariants.yaml"
    text = src_file.read_text()
    _, blocks = split_entries(text)
    gen_all = [genericize(b) for b in blocks]

    def eid(b):
        for l in b:
            if l.startswith("  - id: "):
                return l.split("id:", 1)[1].strip()
        return ""
    gen_meta = [b for b in gen_all if eid(b).startswith("meta.")]

    targets = {
        # ONLY the pack is generated now. The corpus is the hand-authored source.
        root / "cmd/awg/templates/awareness/meta_principles.yaml": render(PACK_HEADER, gen_meta),
    }
    changed = []
    for path, content in targets.items():
        old = path.read_text() if path.exists() else ""
        if old != content:
            changed.append(str(path.relative_to(root)))
            if not a.check:
                path.write_text(content)
    if a.check and changed:
        print("principle pack STALE:", ", ".join(changed))
        sys.exit(1)
    print(f"pack: {len(gen_all)} corpus entries, {len(gen_meta)} meta principles"
          + (f"; updated {len(changed)} file(s): {', '.join(changed)}" if changed else "; up to date"))

if __name__ == "__main__":
    main()
