// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime/debug"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/globulario/sensei/golang/statedir"
)

// The principle pack is authored in docs/awareness/generic/, generated into
// cmd/awg/templates/awareness/meta_principles.yaml by
// scripts/sync-principle-pack.py, and installed into a project by
// `sensei init`. That last hop only ever ran ONCE per project: init copies the
// template only when the destination does not exist, and the sync script writes
// to no project (its --services flag is a retained no-op). So a principle
// authored upstream had no sanctioned route to an ALREADY INSTALLED mirror — a
// correct derivation with no path to its consumer.
//
// `sensei principle-pack refresh` is that missing edge, and it is deliberately
// paranoid about the one thing it cannot see: what the project started from.
//
// WITHOUT A BASELINE, "present upstream and absent locally" IS AMBIGUOUS. It
// may be an upstream addition the project has not received, or an entry the
// project deliberately deleted. Those two states are observationally
// identical, so a baseline-free run reports cause UNKNOWN and refuses to
// apply. A baseline is one of:
//
//   - an install record written by `sensei init` whose pack digest still
//     matches the mirror (the project has not touched it), or
//   - a prior adoption record whose resulting digest still matches the
//     mirror (we put it there and nobody has edited it since), or
//   - an explicit one-time --reconcile-legacy authorization from an operator
//     who has reviewed the divergence themselves.
const (
	principlePackReceiptSchemaVersion = 1
	principlePackReceiptKind          = "principle_pack_adoption"
	principlePackInstallKind          = "principle_pack_install"

	// The generated mirror must announce itself. A file lacking this marker is
	// not a managed mirror and is never written.
	principlePackGeneratedMarker = "GENERATED by scripts/sync-principle-pack.py"

	packTemplatePath = "templates/awareness/meta_principles.yaml"
	mirrorRelPath    = "docs/awareness/meta_principles.yaml"
)

// The principle-pack state lives under the project's ACTIVE state directory
// (statedir.Path — ".sensei", or a pre-existing ".awg" for a legacy repo),
// never a hard-coded ".sensei/..." literal. A literal would create
// ".sensei/principle-pack" even on a repo that only has ".awg", and
// statedir.Name prefers ".sensei" once any directory exists under it —
// so the next command to resolve state would silently stop reading the
// project's real ".awg" configuration. Split-brain, from one hard-coded path.
func principlePackDirPath(root string) string {
	return filepath.Join(statedir.Path(root), "principle-pack")
}

func adoptionsDirPath(root string) string {
	return filepath.Join(principlePackDirPath(root), "adoptions")
}

func installRecordFilePath(root string) string {
	return filepath.Join(principlePackDirPath(root), "installed.yaml")
}

func refreshLockFilePath(root string) string {
	return filepath.Join(principlePackDirPath(root), "refresh.lock")
}

// packDiff is the entry-level comparison between the embedded pack and an
// installed mirror, keyed by canonical id.
type packDiff struct {
	// UpstreamOnly is present upstream and absent locally. Whether that is an
	// upstream ADDITION or a local DELETION cannot be told without a baseline,
	// so the name deliberately does not claim either.
	UpstreamOnly []string
	Changed      []string // shared id whose content differs
	LocalOnly    []string // present locally, absent upstream
	Preamble     bool     // leading comment block differs
	SharedSame   int
}

func (d packDiff) clean() bool {
	return len(d.Changed) == 0 && len(d.LocalOnly) == 0 && !d.Preamble
}

func (d packDiff) conflicting() []string {
	out := append([]string{}, d.Changed...)
	out = append(out, d.LocalOnly...)
	sort.Strings(out)
	return out
}

// principlePackRecord is BOTH the adoption intent and, once the mirror
// matches, the receipt. It is written ONCE, before the mirror is touched, and
// never rewritten. Its terminal disposition is DERIVED by digesting the mirror
// rather than stored — the same move that removed the two-file transaction
// from candidate promotion. A stored status would be a second mutable write
// that can fail independently, which is exactly the partial-apply hole.
type principlePackRecord struct {
	SchemaVersion int    `yaml:"schema_version"`
	Kind          string `yaml:"kind"`
	Source        struct {
		Authority      string `yaml:"authority"`
		SenseiRevision string `yaml:"sensei_revision"`
		PackDigest     string `yaml:"pack_digest_sha256"`
		PrincipleCount int    `yaml:"principle_count"`
	} `yaml:"source"`
	Target struct {
		Path            string `yaml:"path"`
		PreviousDigest  string `yaml:"previous_digest_sha256"`
		ResultingDigest string `yaml:"resulting_digest_sha256"`
	} `yaml:"target"`
	Change struct {
		AddedIDs       []string `yaml:"added_ids"`
		ChangedIDs     []string `yaml:"changed_ids"`
		RemovedIDs     []string `yaml:"removed_ids"`
		ConflictingIDs []string `yaml:"conflicting_ids"`
	} `yaml:"change"`
	Authorization  string `yaml:"authorization"`
	DispositionIs  string `yaml:"disposition_is"`
	DispositionKey string `yaml:"disposition_rule"`
}

// derivedDisposition answers "what happened?" from the mirror itself.
func (r principlePackRecord) derivedDisposition(mirrorDigest string) string {
	switch mirrorDigest {
	case r.Target.ResultingDigest:
		return "applied"
	case r.Target.PreviousDigest:
		return "intent_open" // record written, mirror not yet replaced
	default:
		return "conflict" // mirror is neither end of this transaction
	}
}

type installRecord struct {
	SchemaVersion int      `yaml:"schema_version"`
	Kind          string   `yaml:"kind"`
	PackDigest    string   `yaml:"pack_digest_sha256"`
	PrincipleIDs  []string `yaml:"principle_ids"`
}

func runPrinciplePack(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: sensei principle-pack <refresh> [flags]")
		return 2
	}
	switch args[0] {
	case "refresh":
		return runPrinciplePackRefresh(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "sensei principle-pack: unknown subcommand %q (refresh)\n", args[0])
		return 2
	}
}

func runPrinciplePackRefresh(args []string) int {
	fs := flag.NewFlagSet("sensei principle-pack refresh", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	repo := fs.String("repo", "", "path to the project whose managed principle mirror should be refreshed")
	apply := fs.Bool("apply", false, "write the refreshed mirror and its adoption record (default: plan only)")
	reconcile := fs.Bool("reconcile-legacy", false,
		"authorize a one-time adoption for a mirror with no verified baseline (operator asserts the divergence has been reviewed)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if strings.TrimSpace(*repo) == "" {
		fmt.Fprintln(os.Stderr, "sensei principle-pack refresh: --repo is required")
		return 2
	}
	root, err := filepath.Abs(*repo)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
		return 2
	}
	if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s is not a directory\n", root)
		return 2
	}

	// Exclusive lock for any run that may write. Concurrent agents and editors
	// are a live condition in this codebase, not a theoretical one.
	if *apply {
		release, err := acquireRefreshLock(root)
		if err != nil {
			fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
			return 1
		}
		defer release()
	}

	packBytes, err := templates.ReadFile(packTemplatePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: embedded pack unreadable: %v\n", err)
		return 1
	}
	packEntries, packKey, packPre, err := parsePrinciplePack(packBytes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: embedded pack is malformed: %v\n", err)
		return 1
	}
	packDigest := sha256Hex(packBytes)

	mirrorPath := filepath.Join(root, mirrorRelPath)
	mirrorBytes, err := readManagedMirror(root, mirrorPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
		return 1
	}
	mirrorEntries, mirrorKey, mirrorPre, err := parsePrinciplePack(mirrorBytes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s is not a recognized generated mirror: %v\n", mirrorRelPath, err)
		return 1
	}
	if mirrorKey != packKey {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s has top-level key %q, expected %q\n", mirrorRelPath, mirrorKey, packKey)
		return 1
	}
	if !strings.Contains(mirrorPre, principlePackGeneratedMarker) {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s does not declare itself generated (%q); refusing to write a possibly hand-authored file\n",
			mirrorRelPath, principlePackGeneratedMarker)
		return 1
	}
	mirrorDigest := sha256Hex(mirrorBytes)

	diff := diffPrinciplePack(packEntries, mirrorEntries, packPre, mirrorPre)
	baseline, baselineWhy := verifyBaseline(root, mirrorDigest)

	fmt.Printf("principle-pack refresh\n")
	fmt.Printf("  pack:    %d principles, digest %s\n", len(packEntries), short(packDigest))
	fmt.Printf("  mirror:  %s — %d principles, digest %s\n", mirrorRelPath, len(mirrorEntries), short(mirrorDigest))
	fmt.Printf("  baseline: %s\n", baselineWhy)
	fmt.Printf("  shared identical: %d\n", diff.SharedSame)
	if len(diff.UpstreamOnly) > 0 {
		if baseline {
			reportIDs("  upstream additions", diff.UpstreamOnly)
		} else {
			reportIDs("  present upstream, absent locally — cause: UNKNOWN (no baseline; may be an upstream addition OR a local deletion)", diff.UpstreamOnly)
		}
	}
	reportIDs("  locally changed", diff.Changed)
	reportIDs("  present locally, absent upstream", diff.LocalOnly)
	if diff.Preamble {
		fmt.Printf("  preamble: DIFFERS from the pack\n")
	}

	// Recovery: an open intent from an interrupted apply.
	if rec, found := openIntentFor(root, mirrorDigest, packDigest); found {
		fmt.Printf("\nrecovering an interrupted adoption (intent %s)\n", short(rec.Target.ResultingDigest))
		if !*apply {
			fmt.Printf("disposition: intent_open — re-run with --apply to complete it\n")
			return 0
		}
		if err := commitMirror(root, mirrorPath, mirrorBytes, packBytes); err != nil {
			fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
			return 1
		}
		fmt.Printf("disposition: applied (resumed) — mirror %s → %s\n", short(mirrorDigest), short(packDigest))
		return 0
	}

	if mirrorDigest == packDigest {
		// Current. An --apply replay of a prior successful adoption must not
		// trust that "content is already right" as proof its directory sync
		// ever succeeded -- commitMirror's own rename could have completed
		// with the mirror's final syncDir failing transiently, and this
		// branch would otherwise report success on every retry without ever
		// confirming durability. Plan mode (no --apply) stays read-only, as
		// everywhere else in this command.
		if *apply {
			if err := syncDir(filepath.Dir(mirrorPath)); err != nil {
				fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: re-syncing mirror directory: %v\n", err)
				return 1
			}
		}
		// If an adoption put it here the record exists and derives to
		// "applied"; if not, say so rather than implying evidence we lack.
		if rec, ok := recordForResult(root, packDigest); ok {
			fmt.Printf("\ndisposition: %s — mirror already matches the pack; record %s\n",
				rec.derivedDisposition(mirrorDigest), short(rec.Target.ResultingDigest))
		} else {
			fmt.Printf("\ndisposition: already_current — mirror matches the pack, with no adoption record on file\n")
		}
		return 0
	}

	if !diff.clean() {
		fmt.Fprintf(os.Stderr, "\ndisposition: conflict — refusing to refresh.\n")
		fmt.Fprintf(os.Stderr, "  This mirror is not a clean copy of a previously installed pack, so an\n")
		fmt.Fprintf(os.Stderr, "  automatic refresh could not tell an upstream change from a local edit.\n")
		if ids := diff.conflicting(); len(ids) > 0 {
			fmt.Fprintf(os.Stderr, "  conflicting ids (%d): %s\n", len(ids), strings.Join(ids, ", "))
		}
		if diff.Preamble {
			fmt.Fprintf(os.Stderr, "  the generated preamble also differs from the pack's\n")
		}
		return 1
	}
	if len(diff.UpstreamOnly) == 0 {
		fmt.Fprintf(os.Stderr, "\ndisposition: conflict — entries match but bytes differ (formatting drift); refusing\n")
		return 1
	}

	authorization := "verified_baseline"
	if !baseline {
		if !*reconcile {
			fmt.Fprintf(os.Stderr, "\ndisposition: needs_reconciliation — refusing to apply without a baseline.\n")
			fmt.Fprintf(os.Stderr, "  %d id(s) are present upstream and absent locally, but with no install or\n", len(diff.UpstreamOnly))
			fmt.Fprintf(os.Stderr, "  adoption record matching this mirror there is no way to tell an upstream\n")
			fmt.Fprintf(os.Stderr, "  addition from a deliberate local deletion. Applying would silently\n")
			fmt.Fprintf(os.Stderr, "  resurrect entries the project may have removed on purpose.\n")
			fmt.Fprintf(os.Stderr, "  Review the list above, then re-run with --reconcile-legacy --apply.\n")
			return 1
		}
		authorization = "reconcile_legacy"
	}

	if !*apply {
		fmt.Printf("\ndisposition: plan — %d id(s) would be adopted: %s\n",
			len(diff.UpstreamOnly), strings.Join(diff.UpstreamOnly, ", "))
		fmt.Printf("authorization: %s\n", authorization)
		fmt.Printf("re-run with --apply to write the mirror and its adoption record\n")
		return 0
	}

	// Write the immutable record FIRST. If the mirror write then fails, the
	// record is an open intent and a re-run resumes it — there is no state in
	// which the mirror moved and no evidence exists.
	rec := buildPrinciplePackRecord(packDigest, len(packEntries), mirrorRelPath, mirrorDigest, packDigest, diff, authorization)
	recPath, err := writePrinciplePackRecord(root, rec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: recording adoption intent: %v\n", err)
		fmt.Fprintf(os.Stderr, "  the mirror has NOT been modified\n")
		return 1
	}
	if err := commitMirror(root, mirrorPath, mirrorBytes, packBytes); err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
		fmt.Fprintf(os.Stderr, "  intent %s remains open; re-run with --apply to resume\n", mustRel(root, recPath))
		return 1
	}

	fmt.Printf("\ndisposition: applied\n")
	fmt.Printf("  adopted: %s\n", strings.Join(diff.UpstreamOnly, ", "))
	fmt.Printf("  mirror:  %s → %s\n", short(mirrorDigest), short(packDigest))
	fmt.Printf("  record:  %s (authorization: %s)\n", mustRel(root, recPath), authorization)
	fmt.Printf("\nThe project graph is NOT rebuilt by this command — run the project's own\n")
	fmt.Printf("seed/graph build so the new principles reach their consumers.\n")
	return 0
}

// commitMirror re-validates immediately before the rename and refuses if the
// file moved under us. Read → decide → write is a TOCTOU window, and this repo
// demonstrably has concurrent writers.
//
// The replacement is prepared FIRST — write, sync, chmod a temp file — so
// none of that work sits between the re-check and the rename. Only then is
// the mirror re-read and re-digested, immediately before the one os.Rename
// that commits it. An earlier version re-checked before preparing the
// replacement, leaving the entire write+sync+chmod duration as a window in
// which a concurrent editor's save would be silently overwritten by the
// rename; this ordering shrinks that window to one digest read plus one
// rename syscall. No lock can close it further against an arbitrary external
// editor that does not participate in this repo's own refresh.lock.
var commitMirrorAfterPrepareHook func()

func commitMirror(root, mirrorPath string, expected, next []byte) error {
	dir := filepath.Dir(mirrorPath)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(mirrorPath)+".tmp*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	// Mode set BEFORE write+sync, not after: CreateTemp always creates at
	// 0600, and chmod is itself metadata that is only as durable as the
	// sync that follows it. Chmod-then-sync-content (the old order) synced
	// the content while it was still mode 0600, then changed the mode with
	// no further sync -- a crash between that chmod and the rename could
	// leave the eventual mirror at 0600 instead of 0644, inaccessible to
	// other readers, even though the content itself survived. Setting the
	// mode first means the one Sync below covers both.
	if err := os.Chmod(tmpName, 0o644); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(next); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	// Test-only seam: nil in production. Lets a test deterministically land a
	// concurrent edit exactly between temp-file preparation and the
	// pre-rename re-check below, instead of relying on timing.
	if commitMirrorAfterPrepareHook != nil {
		commitMirrorAfterPrepareHook()
	}

	current, err := readManagedMirror(root, mirrorPath)
	if err != nil {
		return fmt.Errorf("re-reading the mirror immediately before commit: %w", err)
	}
	if sha256Hex(current) != sha256Hex(expected) {
		return fmt.Errorf("the mirror changed while this run was deciding (now %s, expected %s); refusing to overwrite a concurrent edit",
			short(sha256Hex(current)), short(sha256Hex(expected)))
	}
	if err := os.Rename(tmpName, mirrorPath); err != nil {
		return err
	}
	return syncDir(dir)
}

// readManagedMirror refuses symlinks and irregular files rather than following
// them, so a replaced path cannot redirect a read or a later write. This
// covers not just the leaf file but every parent directory component
// between root and the leaf: Lstat-ing only the leaf would let a symlinked
// "docs" or "docs/awareness" pass this check while the actual read and the
// later rename still traverse it, redirecting outside root.
func readManagedMirror(root, path string) ([]byte, error) {
	if err := refuseSymlinkedAncestors(root, path); err != nil {
		return nil, err
	}
	fi, err := os.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("no managed mirror at %s (%v)", mirrorRelPath, err)
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s is a symlink; refusing to read or write through it", mirrorRelPath)
	}
	if !fi.Mode().IsRegular() {
		return nil, fmt.Errorf("%s is not a regular file", mirrorRelPath)
	}
	return os.ReadFile(path)
}

// refuseSymlinkedAncestors Lstats every directory component strictly
// between root and path (exclusive of both), refusing if any is a symlink
// or anything other than a real directory. path itself is not checked
// here -- callers Lstat the leaf separately, since leaf handling differs
// (a file for the mirror, a directory for state-dir creation).
func refuseSymlinkedAncestors(root, path string) error {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return fmt.Errorf("resolve %s relative to %s: %w", path, root, err)
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("%s escapes %s", path, root)
	}
	dir := filepath.Dir(rel)
	if dir == "." {
		return nil // leaf lives directly under root, nothing intermediate to check
	}
	cur := root
	for _, part := range strings.Split(dir, string(filepath.Separator)) {
		cur = filepath.Join(cur, part)
		fi, err := os.Lstat(cur)
		if err != nil {
			return fmt.Errorf("no managed mirror parent at %s (%v)", cur, err)
		}
		if fi.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s is a symlink; refusing to read or write through it", cur)
		}
		if !fi.IsDir() {
			return fmt.Errorf("%s is not a directory", cur)
		}
	}
	return nil
}

func acquireRefreshLock(root string) (func(), error) {
	// mkdirAllSynced, not plain MkdirAll: this may be the FIRST thing in the
	// whole run to create principle-pack/ (e.g. --reconcile-legacy --apply
	// on a project with no prior baseline or adoption at all). If that
	// creation is not made durable here, a later mkdirAllSynced call for the
	// adoptions/ receipt sees principle-pack/ already exists and has no way
	// to know its own creation was never confirmed -- a crash could then
	// preserve a synced, applied mirror while losing the unsynced
	// principle-pack/ entry (and everything durability-managed under it,
	// including the receipt). The lock file ITSELF is still ephemeral, but
	// the directory it happens to be first to create is not, the moment
	// real evidence gets stored under it later in the same run.
	if err := mkdirAllSynced(principlePackDirPath(root), statedir.Path(root), 0o755); err != nil {
		return nil, err
	}
	lock := refreshLockFilePath(root)
	f, err := os.OpenFile(lock, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o644)
	if err != nil {
		if os.IsExist(err) {
			return nil, fmt.Errorf("another refresh holds %s; remove it if no refresh is running", lock)
		}
		return nil, err
	}
	fmt.Fprintf(f, "pid %d\n", os.Getpid())
	f.Close()
	return func() { os.Remove(lock) }, nil
}

// parsePrinciplePack enforces an EXACT document shape. Anything it merely
// ignored could be silently deleted by a whole-document replacement — a
// project's extra top-level key must refuse the refresh, not vanish in it.
func parsePrinciplePack(b []byte) (map[string]map[string]any, string, string, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, "", "", err
	}
	if len(doc) == 0 {
		return nil, "", "", fmt.Errorf("empty document")
	}
	if len(doc) != 1 {
		keys := make([]string, 0, len(doc))
		for k := range doc {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		return nil, "", "", fmt.Errorf("expected exactly one top-level key, found %d (%s); "+
			"a whole-document refresh would discard the others", len(keys), strings.Join(keys, ", "))
	}
	var key string
	for k := range doc {
		key = k
	}
	list, ok := doc[key].([]any)
	if !ok {
		return nil, "", "", fmt.Errorf("top-level key %q is not a list of principles", key)
	}
	entries := map[string]map[string]any{}
	for i, raw := range list {
		m, ok := raw.(map[string]any)
		if !ok {
			return nil, "", "", fmt.Errorf("entry %d under %q is not a mapping", i, key)
		}
		id, ok := m["id"].(string)
		if !ok || strings.TrimSpace(id) == "" {
			return nil, "", "", fmt.Errorf("entry %d under %q has no string id", i, key)
		}
		if _, dup := entries[id]; dup {
			return nil, "", "", fmt.Errorf("duplicate id %q", id)
		}
		entries[id] = m
	}
	return entries, key, leadingComments(b), nil
}

func leadingComments(b []byte) string {
	var out []string
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(line)
		if t == "" {
			continue
		}
		if !strings.HasPrefix(t, "#") {
			break
		}
		out = append(out, t)
	}
	return strings.Join(out, "\n")
}

func diffPrinciplePack(pack, mirror map[string]map[string]any, packPre, mirrorPre string) packDiff {
	d := packDiff{Preamble: packPre != mirrorPre}
	for id, pe := range pack {
		me, ok := mirror[id]
		if !ok {
			d.UpstreamOnly = append(d.UpstreamOnly, id)
			continue
		}
		if reflect.DeepEqual(pe, me) {
			d.SharedSame++
		} else {
			d.Changed = append(d.Changed, id)
		}
	}
	for id := range mirror {
		if _, ok := pack[id]; !ok {
			d.LocalOnly = append(d.LocalOnly, id)
		}
	}
	sort.Strings(d.UpstreamOnly)
	sort.Strings(d.Changed)
	sort.Strings(d.LocalOnly)
	return d
}

// verifyBaseline answers "do we know what this mirror started from?"
func verifyBaseline(root, mirrorDigest string) (bool, string) {
	var ir installRecord
	if b, err := os.ReadFile(installRecordFilePath(root)); err == nil {
		if yaml.Unmarshal(b, &ir) == nil && ir.PackDigest == mirrorDigest {
			return true, "verified (install record digest matches the mirror)"
		}
	}
	for _, rec := range loadRecords(root) {
		if rec.Target.ResultingDigest == mirrorDigest {
			return true, "verified (prior adoption record " + short(rec.Target.ResultingDigest) + " matches the mirror)"
		}
	}
	return false, "NONE — no install or adoption record matches this mirror"
}

func loadRecords(root string) []principlePackRecord {
	matches, _ := filepath.Glob(filepath.Join(adoptionsDirPath(root), "*.yaml"))
	var out []principlePackRecord
	for _, m := range matches {
		b, err := os.ReadFile(m)
		if err != nil {
			continue
		}
		var r principlePackRecord
		if yaml.Unmarshal(b, &r) == nil && r.Kind == principlePackReceiptKind {
			out = append(out, r)
		}
	}
	return out
}

func recordForResult(root, digest string) (principlePackRecord, bool) {
	for _, r := range loadRecords(root) {
		if r.Target.ResultingDigest == digest {
			return r, true
		}
	}
	return principlePackRecord{}, false
}

// openIntentFor finds a record whose mirror move has not happened yet.
func openIntentFor(root, mirrorDigest, packDigest string) (principlePackRecord, bool) {
	for _, r := range loadRecords(root) {
		if r.Target.PreviousDigest == mirrorDigest && r.Target.ResultingDigest == packDigest &&
			r.derivedDisposition(mirrorDigest) == "intent_open" {
			return r, true
		}
	}
	return principlePackRecord{}, false
}

func buildPrinciplePackRecord(packDigest string, count int, path, prev, next string, d packDiff, authorization string) principlePackRecord {
	var r principlePackRecord
	r.SchemaVersion = principlePackReceiptSchemaVersion
	r.Kind = principlePackReceiptKind
	r.Source.Authority = "github.com/globulario/sensei"
	r.Source.SenseiRevision = senseiRevision()
	r.Source.PackDigest = packDigest
	r.Source.PrincipleCount = count
	r.Target.Path = path
	r.Target.PreviousDigest = prev
	r.Target.ResultingDigest = next
	r.Change.AddedIDs = nonNil(d.UpstreamOnly)
	r.Change.ChangedIDs = nonNil(d.Changed)
	r.Change.RemovedIDs = nonNil(d.LocalOnly)
	r.Change.ConflictingIDs = nonNil(d.conflicting())
	r.Authorization = authorization
	r.DispositionIs = "derived"
	r.DispositionKey = "applied when the mirror digests to resulting_digest_sha256; " +
		"intent_open when it digests to previous_digest_sha256; conflict otherwise"
	return r
}

const principlePackRecordHeader = "# Immutable adoption record written by `sensei principle-pack refresh`.\n" +
	"# Written BEFORE the mirror is replaced, and never rewritten: its terminal\n" +
	"# disposition is derived by digesting the mirror, not stored here. Evidence\n" +
	"# that an upstream-authored pack reached this project — not an authority for\n" +
	"# the principles themselves.\n"

// writePrinciplePackRecord writes the immutable, digest-named record. Replay of
// an identical adoption finds it already present and does not rewrite.
func writePrinciplePackRecord(root string, r principlePackRecord) (string, error) {
	dir := adoptionsDirPath(root)
	if err := mkdirAllSynced(dir, statedir.Path(root), 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, short(r.Target.ResultingDigest)+".yaml")
	body, err := yaml.Marshal(r)
	if err != nil {
		return "", err
	}
	full := principlePackRecordHeader + string(body)
	switch existing, err := os.ReadFile(path); {
	case err == nil:
		if string(existing) == full {
			// Exact replay: the receipt's own bytes are already right, but
			// that says nothing about whether the directory sync after the
			// rename that wrote them ever actually succeeded. If a prior run
			// renamed the receipt into place and then hit a transient sync
			// error, a naive replay would return success here without ever
			// retrying the sync -- silently forgetting a failed durability
			// step and letting the caller proceed to commitMirror believing
			// the receipt is durable when it was never confirmed.
			if err := syncDir(dir); err != nil {
				return "", fmt.Errorf("re-syncing existing receipt directory: %w", err)
			}
			return path, nil // exact replay
		}
		return "", fmt.Errorf("record %s already exists with different content; refusing to overwrite", path)
	case os.IsNotExist(err):
		// Fall through to create it below.
	default:
		// Exists but could not be read (permissions, a transient I/O error,
		// anything not "absent"). This record is documented as immutable
		// evidence; only proven absence may create one. Falling through to
		// atomicWriteFile here would rename over content this process never
		// actually verified, destroying potentially conflicting evidence
		// instead of refusing on an honest "I don't know what's there".
		return "", fmt.Errorf("record %s exists but could not be read; refusing to overwrite: %w", path, err)
	}
	if err := atomicWriteFile(path, []byte(full), 0o644); err != nil {
		return "", err
	}
	if _, err := os.ReadFile(path); err != nil {
		return "", err
	}
	return path, nil
}

// writeInstallRecord records the exact pack a project was initialized from, so
// a later refresh can prove the mirror is untouched. Without it, "absent
// locally" stays ambiguous forever.
func writeInstallRecord(root string, packBytes []byte) error {
	entries, _, _, err := parsePrinciplePack(packBytes)
	if err != nil {
		return err
	}
	ids := make([]string, 0, len(entries))
	for id := range entries {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var ir installRecord
	ir.SchemaVersion = principlePackReceiptSchemaVersion
	ir.Kind = principlePackInstallKind
	ir.PackDigest = sha256Hex(packBytes)
	ir.PrincipleIDs = ids
	body, err := yaml.Marshal(ir)
	if err != nil {
		return err
	}
	path := installRecordFilePath(root)
	if err := mkdirAllSynced(filepath.Dir(path), statedir.Path(root), 0o755); err != nil {
		return err
	}
	header := "# Baseline written by `sensei init`: the exact principle pack this project\n" +
		"# was initialized from. `sensei principle-pack refresh` uses it to prove the\n" +
		"# mirror is an untouched projection before adopting upstream changes.\n"
	return atomicWriteFile(path, []byte(header+string(body)), 0o644)
}

func atomicWriteFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	// Mode set BEFORE write+sync, not after -- see commitMirror's identical
	// comment. A chmod with no sync of its own is only as durable as the
	// next thing that happens to sync it; putting it first means the
	// content sync below covers both.
	if err := os.Chmod(tmpName, mode); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return err
	}
	return syncDir(dir)
}

// syncDir fsyncs a directory's own entry so a preceding rename INTO it is
// durable across a crash, not merely visible in the page cache. rename(2) is
// atomic (a reader never observes a torn result) but not durable by itself:
// without this, a crash right after a successful rename can still lose that
// directory entry, reverting to whatever the name pointed at before.
//
// A package-level var, not a plain func: tests override it to prove a
// caller retries or surfaces a failed sync rather than silently treating
// already-correct file bytes as proof the directory itself was made
// durable. Never overridden in production. The real implementation is
// platform-specific (dirsync_unix.go / dirsync_windows.go) -- an
// os.Open+File.Sync directory handle is fsync-able on Unix but not on
// Windows (FlushFileBuffers cannot flush a read-only directory handle), and
// NTFS's own metadata journaling does not need or support the same
// explicit directory-entry flush ext4-family filesystems require.
var syncDir = syncDirImpl

// mkdirAllSynced is os.MkdirAll plus durability, unconditionally: every
// directory level from path up to and including boundary is synced after
// MkdirAll, whether or not THIS call is what created it. A directory
// already being visible on disk is not proof its creation was ever made
// durable -- a previous attempt may have created it and then failed the
// sync itself (a transient error, a crash), and there is no on-disk marker
// distinguishing "exists and durable" from "exists and never confirmed".
// Trying to be clever about syncing only newly-created levels was exactly
// that bug: a retry saw the level already existed and silently skipped
// resyncing it. Unconditional, idempotent resyncing is the only fully
// correct answer, and cheap enough at this call frequency that the
// redundant work is not worth optimizing away. boundary must be an
// ancestor of path that this function is not responsible for (typically
// the project's state directory root) -- callers never durability-manage
// past their own subtree.
func mkdirAllSynced(path, boundary string, perm os.FileMode) error {
	if err := os.MkdirAll(path, perm); err != nil {
		return err
	}
	boundary = filepath.Clean(boundary)
	for p := filepath.Clean(path); p != boundary; {
		parent := filepath.Dir(p)
		if err := syncDir(parent); err != nil {
			return fmt.Errorf("syncing %s: %w", parent, err)
		}
		if parent == p {
			return fmt.Errorf("mkdirAllSynced: %s is not under boundary %s", path, boundary)
		}
		p = parent
	}
	return nil
}

func senseiRevision() string {
	if bi, ok := debug.ReadBuildInfo(); ok {
		for _, s := range bi.Settings {
			if s.Key == "vcs.revision" && s.Value != "" {
				return s.Value
			}
		}
	}
	return Version
}

func nonNil(in []string) []string {
	if in == nil {
		return []string{}
	}
	return in
}

func mustRel(root, path string) string {
	if rel, err := filepath.Rel(root, path); err == nil {
		return rel
	}
	return path
}

func reportIDs(label string, ids []string) {
	if len(ids) == 0 {
		return
	}
	fmt.Printf("%s (%d): %s\n", label, len(ids), strings.Join(ids, ", "))
}
