// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime/debug"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// The principle pack is authored in docs/awareness/generic/, generated into
// cmd/awg/templates/awareness/meta_principles.yaml by
// scripts/sync-principle-pack.py, and installed into a new project by
// `sensei init`. That last hop only ever ran ONCE per project: init copies the
// template only when the destination does not exist, and the sync script does
// not write to any project (its --services flag is a retained no-op). So a
// canonical principle authored upstream had no sanctioned path to an ALREADY
// INSTALLED project mirror — a correct derivation with no route to its
// consumer.
//
// `sensei principle-pack refresh` is that missing edge. It is deliberately
// narrow: it can carry upstream ADDITIONS into a mirror that is otherwise
// byte-for-byte the pack it was installed from, it emits a receipt binding
// both digests, and it refuses everything else. It does not merge YAML, does
// not resolve conflicts, and does not touch a project's candidate ledger.

const (
	principlePackReceiptSchemaVersion = 1
	principlePackReceiptKind          = "principle_pack_adoption"

	// The generated mirror must announce itself. A file that does not carry
	// this marker is not a managed mirror and is never written.
	principlePackGeneratedMarker = "GENERATED by scripts/sync-principle-pack.py"

	packTemplatePath = "templates/awareness/meta_principles.yaml"
	mirrorRelPath    = "docs/awareness/meta_principles.yaml"
	receiptRelDir    = ".sensei/principle-pack/adoptions"
)

// packDiff is the entry-level comparison between the embedded pack and an
// installed mirror, keyed by canonical id.
type packDiff struct {
	Added      []string // in pack, absent from mirror — the only auto-appliable class
	Changed    []string // shared id whose content differs
	Removed    []string // in mirror, absent from pack
	Preamble   bool     // leading comment block differs
	SharedSame int
}

func (d packDiff) clean() bool {
	return len(d.Changed) == 0 && len(d.Removed) == 0 && !d.Preamble
}

func (d packDiff) conflicting() []string {
	out := append([]string{}, d.Changed...)
	out = append(out, d.Removed...)
	sort.Strings(out)
	return out
}

type principlePackReceipt struct {
	SchemaVersion int    `yaml:"schema_version"`
	Kind          string `yaml:"kind"`
	Source        struct {
		Authority      string `yaml:"authority"`
		SenseiRevision string `yaml:"sensei_revision"`
		PackDigest     string `yaml:"pack_digest_sha256"`
		PrincipleCount int    `yaml:"principle_count"`
	} `yaml:"source"`
	Target struct {
		Path            string `yaml:"path"`
		PreviousDigest  string `yaml:"previous_digest_sha256"`
		ResultingDigest string `yaml:"resulting_digest_sha256"`
	} `yaml:"target"`
	Change struct {
		AddedIDs       []string `yaml:"added_ids"`
		ChangedIDs     []string `yaml:"changed_ids"`
		RemovedIDs     []string `yaml:"removed_ids"`
		ConflictingIDs []string `yaml:"conflicting_ids"`
	} `yaml:"change"`
	Disposition string `yaml:"disposition"`
}

func runPrinciplePack(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: sensei principle-pack <refresh> [flags]")
		return 2
	}
	switch args[0] {
	case "refresh":
		return runPrinciplePackRefresh(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "sensei principle-pack: unknown subcommand %q (refresh)\n", args[0])
		return 2
	}
}

func runPrinciplePackRefresh(args []string) int {
	fs := flag.NewFlagSet("sensei principle-pack refresh", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	repo := fs.String("repo", "", "path to the project whose managed principle mirror should be refreshed")
	apply := fs.Bool("apply", false, "write the refreshed mirror and its adoption receipt (default: plan only)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if strings.TrimSpace(*repo) == "" {
		fmt.Fprintln(os.Stderr, "sensei principle-pack refresh: --repo is required")
		return 2
	}
	root, err := filepath.Abs(*repo)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %v\n", err)
		return 2
	}
	if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s is not a directory\n", root)
		return 2
	}

	packBytes, err := templates.ReadFile(packTemplatePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: embedded pack unreadable: %v\n", err)
		return 1
	}

	mirrorPath := filepath.Join(root, mirrorRelPath)

	// A symlinked destination would let a replaced path redirect the write
	// outside the project. Refuse before reading, and never follow it.
	if fi, err := os.Lstat(mirrorPath); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s is a symlink; refusing to write through it\n", mirrorRelPath)
		return 1
	}
	mirrorBytes, err := os.ReadFile(mirrorPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: no managed mirror at %s (%v)\n", mirrorRelPath, err)
		return 1
	}

	packEntries, packKey, packPre, err := parsePrinciplePack(packBytes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: embedded pack is malformed: %v\n", err)
		return 1
	}
	mirrorEntries, mirrorKey, mirrorPre, err := parsePrinciplePack(mirrorBytes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s is not a recognized generated mirror: %v\n", mirrorRelPath, err)
		return 1
	}
	if mirrorKey != packKey {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s has top-level key %q, expected %q\n",
			mirrorRelPath, mirrorKey, packKey)
		return 1
	}
	if !strings.Contains(mirrorPre, principlePackGeneratedMarker) {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: %s does not declare itself generated (%q); refusing to write a hand-authored file\n",
			mirrorRelPath, principlePackGeneratedMarker)
		return 1
	}

	diff := diffPrinciplePack(packEntries, mirrorEntries, packPre, mirrorPre)
	packDigest := sha256Hex(packBytes)
	mirrorDigest := sha256Hex(mirrorBytes)

	fmt.Printf("principle-pack refresh\n")
	fmt.Printf("  pack:    %d principles, digest %s\n", len(packEntries), short(packDigest))
	fmt.Printf("  mirror:  %s — %d principles, digest %s\n", mirrorRelPath, len(mirrorEntries), short(mirrorDigest))
	fmt.Printf("  shared identical: %d\n", diff.SharedSame)
	reportIDs("  upstream additions", diff.Added)
	reportIDs("  locally changed", diff.Changed)
	reportIDs("  present locally, absent upstream", diff.Removed)
	if diff.Preamble {
		fmt.Printf("  preamble: DIFFERS from the pack\n")
	}

	// Already exactly the pack: nothing to do, and rerunning must not write.
	if mirrorDigest == packDigest {
		fmt.Printf("\ndisposition: already_current — mirror is byte-identical to the embedded pack; no write\n")
		return 0
	}

	if !diff.clean() {
		fmt.Fprintf(os.Stderr, "\ndisposition: conflict — refusing to refresh.\n")
		fmt.Fprintf(os.Stderr, "  This mirror is not a clean copy of a previously installed pack, so an\n")
		fmt.Fprintf(os.Stderr, "  automatic refresh could not tell an upstream change from a local edit.\n")
		if ids := diff.conflicting(); len(ids) > 0 {
			fmt.Fprintf(os.Stderr, "  conflicting ids (%d): %s\n", len(ids), strings.Join(ids, ", "))
		}
		if diff.Preamble {
			fmt.Fprintf(os.Stderr, "  the generated preamble also differs from the pack's\n")
		}
		fmt.Fprintf(os.Stderr, "  Reconcile by hand, then re-run.\n")
		return 1
	}

	if len(diff.Added) == 0 {
		// Clean, no additions, yet digests differ: formatting-only drift. Not
		// something this command is chartered to normalize.
		fmt.Fprintf(os.Stderr, "\ndisposition: conflict — entries match but bytes differ (formatting drift); refusing\n")
		return 1
	}

	if !*apply {
		fmt.Printf("\ndisposition: plan — %d upstream addition(s) would be applied: %s\n",
			len(diff.Added), strings.Join(diff.Added, ", "))
		fmt.Printf("re-run with --apply to write the mirror and its adoption receipt\n")
		return 0
	}

	// Safe to apply. Because every shared entry is identical, there are no
	// local extras and the preamble matches, the refreshed mirror IS the pack
	// — no YAML merging, no heuristics.
	if err := atomicWriteFile(mirrorPath, packBytes, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: writing mirror: %v\n", err)
		return 1
	}

	receipt := buildPrinciplePackReceipt(packDigest, len(packEntries), mirrorRelPath, mirrorDigest, packDigest, diff)
	receiptPath, err := writePrinciplePackReceipt(root, receipt)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sensei principle-pack refresh: mirror written but receipt FAILED: %v\n", err)
		fmt.Fprintf(os.Stderr, "  re-run to emit the missing receipt for the now-current mirror\n")
		return 1
	}

	fmt.Printf("\ndisposition: applied\n")
	fmt.Printf("  added:   %s\n", strings.Join(diff.Added, ", "))
	fmt.Printf("  mirror:  %s → %s\n", short(mirrorDigest), short(packDigest))
	fmt.Printf("  receipt: %s\n", mustRel(root, receiptPath))
	fmt.Printf("\nThe project graph is NOT rebuilt by this command — run the project's own\n")
	fmt.Printf("seed/graph build so the new principle reaches its consumers.\n")
	return 0
}

// parsePrinciplePack returns entries by id, the single top-level list key, and
// the leading comment block.
func parsePrinciplePack(b []byte) (map[string]map[string]any, string, string, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, "", "", err
	}
	var key string
	for k, v := range doc {
		if _, ok := v.([]any); ok {
			if key != "" {
				return nil, "", "", fmt.Errorf("expected exactly one top-level list, found %q and %q", key, k)
			}
			key = k
		}
	}
	if key == "" {
		return nil, "", "", fmt.Errorf("no top-level list of principles")
	}
	entries := map[string]map[string]any{}
	for _, raw := range doc[key].([]any) {
		m, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		id, _ := m["id"].(string)
		if id == "" {
			return nil, "", "", fmt.Errorf("entry without an id")
		}
		if _, dup := entries[id]; dup {
			return nil, "", "", fmt.Errorf("duplicate id %q", id)
		}
		entries[id] = m
	}
	return entries, key, leadingComments(b), nil
}

func leadingComments(b []byte) string {
	var out []string
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(line)
		if t == "" {
			continue
		}
		if !strings.HasPrefix(t, "#") {
			break
		}
		out = append(out, t)
	}
	return strings.Join(out, "\n")
}

func diffPrinciplePack(pack, mirror map[string]map[string]any, packPre, mirrorPre string) packDiff {
	d := packDiff{Preamble: packPre != mirrorPre}
	for id, pe := range pack {
		me, ok := mirror[id]
		if !ok {
			d.Added = append(d.Added, id)
			continue
		}
		if reflect.DeepEqual(pe, me) {
			d.SharedSame++
		} else {
			d.Changed = append(d.Changed, id)
		}
	}
	for id := range mirror {
		if _, ok := pack[id]; !ok {
			d.Removed = append(d.Removed, id)
		}
	}
	sort.Strings(d.Added)
	sort.Strings(d.Changed)
	sort.Strings(d.Removed)
	return d
}

func buildPrinciplePackReceipt(packDigest string, count int, path, prev, next string, d packDiff) principlePackReceipt {
	var r principlePackReceipt
	r.SchemaVersion = principlePackReceiptSchemaVersion
	r.Kind = principlePackReceiptKind
	r.Source.Authority = "github.com/globulario/sensei"
	r.Source.SenseiRevision = senseiRevision()
	r.Source.PackDigest = packDigest
	r.Source.PrincipleCount = count
	r.Target.Path = path
	r.Target.PreviousDigest = prev
	r.Target.ResultingDigest = next
	r.Change.AddedIDs = nonNil(d.Added)
	r.Change.ChangedIDs = nonNil(d.Changed)
	r.Change.RemovedIDs = nonNil(d.Removed)
	r.Change.ConflictingIDs = nonNil(d.conflicting())
	r.Disposition = "applied"
	return r
}

// writePrinciplePackReceipt writes an immutable, digest-named receipt. Replay
// of an identical adoption finds the file already present and does not rewrite.
func writePrinciplePackReceipt(root string, r principlePackReceipt) (string, error) {
	dir := filepath.Join(root, receiptRelDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, short(r.Target.ResultingDigest)+".yaml")
	body, err := yaml.Marshal(r)
	if err != nil {
		return "", err
	}
	header := "# Immutable adoption receipt written by `sensei principle-pack refresh`.\n" +
		"# Evidence that an upstream-authored principle pack reached this project's\n" +
		"# managed mirror. Not an authority for the principles themselves.\n"
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == header+string(body) {
			return path, nil // exact replay
		}
		return "", fmt.Errorf("receipt %s already exists with different content; refusing to overwrite", path)
	}
	if err := atomicWriteFile(path, []byte(header+string(body)), 0o644); err != nil {
		return "", err
	}
	if _, err := os.ReadFile(path); err != nil {
		return "", err
	}
	return path, nil
}

func atomicWriteFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, mode); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func senseiRevision() string {
	if bi, ok := debug.ReadBuildInfo(); ok {
		for _, s := range bi.Settings {
			if s.Key == "vcs.revision" && s.Value != "" {
				return s.Value
			}
		}
	}
	return Version
}

func nonNil(in []string) []string {
	if in == nil {
		return []string{}
	}
	return in
}

func mustRel(root, path string) string {
	if rel, err := filepath.Rel(root, path); err == nil {
		return rel
	}
	return path
}

func reportIDs(label string, ids []string) {
	if len(ids) == 0 {
		return
	}
	fmt.Printf("%s (%d): %s\n", label, len(ids), strings.Join(ids, ", "))
}
