package main

// The W3 root cause, fixed at the side that is actually wrong.
//
// `import` always passed `.sensei/project` as a corpus input, and every registered
// domain allows only `docs/awareness`, so the publication gate refused every scoped
// load import generated. I first recorded this as an owner's decision about the
// allowlist. It is not: `.sensei/project` is GENERATED reconstruction output, not
// corpus the repository authored and committed, and publishing generated bytes as
// corpus is precisely what the gate exists to refuse. The gate is right; the caller
// is wrong.
//
// So import filters its inputs to what the domain admits, and says what it dropped
// and what that costs — because silently dropping the reconstruction output would
// hide the fact that code-symbol coverage is not being published.

import (
	"strings"
	"testing"
)

func TestInputsAreFilteredToWhatTheDomainAdmits(t *testing.T) {
	all := []string{"/r/docs/awareness", "/r/docs/awareness/generated", "/r/.sensei/project"}
	kept, dropped := admissibleCorpusInputs("/r", all, []string{"docs/awareness"})

	if len(kept) != 2 || kept[0] != "/r/docs/awareness" || kept[1] != "/r/docs/awareness/generated" {
		t.Errorf("kept %v; both docs/awareness roots are admitted", kept)
	}
	if len(dropped) != 1 || dropped[0] != "/r/.sensei/project" {
		t.Errorf("dropped %v; only .sensei/project is outside the allowed roots", dropped)
	}
}

// An empty allowlist means the domain constrains nothing, and filtering must not
// invent a constraint the registry did not state.
func TestAnUnconstrainedDomainKeepsEveryInput(t *testing.T) {
	all := []string{"/r/docs/awareness", "/r/.sensei/project"}
	kept, dropped := admissibleCorpusInputs("/r", all, nil)
	if len(kept) != 2 || len(dropped) != 0 {
		t.Errorf("kept %v dropped %v; an unconstrained domain admits everything", kept, dropped)
	}
}

// Dropping the reconstruction output is not free, and the notice must say so. A
// silent filter would turn "your coverage was not published" into "the load
// succeeded".
func TestTheDroppedInputsAreReportedWithTheirCost(t *testing.T) {
	notice := droppedInputsNotice([]string{"/r/.sensei/project"}, []string{"docs/awareness"})
	if notice == "" {
		t.Fatal("inputs were dropped silently")
	}
	for _, want := range []string{".sensei/project", "docs/awareness", "not published"} {
		if !strings.Contains(notice, want) {
			t.Errorf("the notice omits %q: %q", want, notice)
		}
	}
	// It must say what is missing as a consequence, not merely that a path was
	// skipped: the whole point is that code-symbol coverage does not reach the graph.
	if !strings.Contains(notice, "coverage") {
		t.Errorf("the notice does not name what is lost: %q", notice)
	}
	// Nothing dropped, nothing said.
	if droppedInputsNotice(nil, []string{"docs/awareness"}) != "" {
		t.Error("a notice was produced when nothing was dropped")
	}
}
