package main

// The W3 root cause, fixed at the side that is actually wrong.
//
// `import` always passed `.sensei/project` as a corpus input, and every registered
// domain allows only `docs/awareness`, so the publication gate refused every scoped
// load import generated. I first recorded this as an owner's decision about the
// allowlist. It is not: `.sensei/project` is GENERATED reconstruction output, not
// corpus the repository authored and committed, and publishing generated bytes as
// corpus is precisely what the gate exists to refuse. The gate is right; the caller
// is wrong.
//
// So import filters its inputs to what the domain admits, and says what it dropped
// and what that costs — because silently dropping the reconstruction output would
// hide the fact that code-symbol coverage is not being published.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInputsAreFilteredToWhatTheDomainAdmits(t *testing.T) {
	all := []string{"/r/docs/awareness", "/r/docs/awareness/generated", "/r/.sensei/project"}
	kept, dropped := admissibleCorpusInputs("/r", all, []string{"docs/awareness"})

	if len(kept) != 2 || kept[0] != "/r/docs/awareness" || kept[1] != "/r/docs/awareness/generated" {
		t.Errorf("kept %v; both docs/awareness roots are admitted", kept)
	}
	if len(dropped) != 1 || dropped[0] != "/r/.sensei/project" {
		t.Errorf("dropped %v; only .sensei/project is outside the allowed roots", dropped)
	}
}

// An empty allowlist means the domain constrains nothing, and filtering must not
// invent a constraint the registry did not state.
func TestAnUnconstrainedDomainKeepsEveryInput(t *testing.T) {
	all := []string{"/r/docs/awareness", "/r/.sensei/project"}
	kept, dropped := admissibleCorpusInputs("/r", all, nil)
	if len(kept) != 2 || len(dropped) != 0 {
		t.Errorf("kept %v dropped %v; an unconstrained domain admits everything", kept, dropped)
	}
}

// Dropping the reconstruction output is not free, and the notice must say so. A
// silent filter would turn "your coverage was not published" into "the load
// succeeded".
func TestTheDroppedInputsAreReportedWithTheirCost(t *testing.T) {
	notice := droppedInputsNotice([]string{"/r/.sensei/project"}, []string{"docs/awareness"})
	if notice == "" {
		t.Fatal("inputs were dropped silently")
	}
	for _, want := range []string{".sensei/project", "docs/awareness", "not published"} {
		if !strings.Contains(notice, want) {
			t.Errorf("the notice omits %q: %q", want, notice)
		}
	}
	// It must say what is missing as a consequence, not merely that a path was
	// skipped: the whole point is that code-symbol coverage does not reach the graph.
	if !strings.Contains(notice, "coverage") {
		t.Errorf("the notice does not name what is lost: %q", notice)
	}
	// Nothing dropped, nothing said.
	if droppedInputsNotice(nil, []string{"docs/awareness"}) != "" {
		t.Error("a notice was produced when nothing was dropped")
	}
}

// REVIEW FINDING (P1, chatgpt-codex-connector, cmd_import.go:216):
// "Avoid admitting generated directories before creating them."
//
// The advertised one-command import-and-load flow bootstraps a foreign checkout: the
// generated corpus and the reconstruction output do not exist until stages 2-4 create
// them. The preflight nevertheless hands those paths to AdmitPublication, whose
// ResolveSourceIdentity runs `git -C <dir> rev-parse --show-toplevel` per directory and
// refuses a path that is not inside a repository -- which a nonexistent directory is not.
//
// So admission refuses the very flow importWouldDefeatItself is written to allow, and it
// refuses it for a reason that has nothing to do with governance: the directory has not
// been written yet.
//
// The fix must not relax admission. A planned root that does not exist yet carries no
// bytes to certify, so it cannot be a corpus root for THIS run -- it is simply not part
// of the input set, and the set is what admission must be asked about.
func TestAPlannedRootThatDoesNotExistYetIsNotAnInputForThisRun(t *testing.T) {
	repo := gitRepo(t, "git@github.com:acme/thing.git")
	present := filepath.Join(repo, "docs", "awareness")
	future := filepath.Join(repo, "docs", "awareness", "generated") // created by a later stage
	absent := filepath.Join(repo, ".sensei", "project")             // ditto

	// Precondition: the fixture really has only the first of the three.
	for _, p := range []string{future, absent} {
		if _, err := os.Stat(p); err == nil {
			t.Fatalf("fixture error: %s already exists", p)
		}
	}

	// The composition the command performs: existence, then the allowlist.
	present2, absent2 := existingCorpusInputs([]string{present, future, absent})
	inputs, dropped := admissibleCorpusInputs(repo, present2, []string{"docs/awareness"})
	dropped = append(dropped, absent2...)
	for _, in := range inputs {
		if in == future || in == absent {
			t.Errorf("a directory that does not exist yet was offered to admission as a corpus root: %s", in)
		}
	}
	if len(inputs) == 0 {
		t.Fatal("the present corpus root was dropped too; admission would have nothing to admit")
	}
	_ = dropped
}

// And the consequence the reviewer actually cares about: admission must SUCCEED for a
// bootstrap-shaped run, rather than refusing because a later stage has not written yet.
func TestAdmissionSucceedsWhenOnlyTheExistingCorpusIsOffered(t *testing.T) {
	repo := gitRepo(t, "git@github.com:acme/thing.git")
	registry := writeRegistryFixture(t, `domains:
    github.com/acme/thing:
        repository_identity: acme/thing
        allowed_corpus_roots:
            - docs/awareness
`)
	all := []string{
		filepath.Join(repo, "docs", "awareness"),
		filepath.Join(repo, "docs", "awareness", "generated"),
		filepath.Join(repo, ".sensei", "project"),
	}
	presentAll, _ := existingCorpusInputs(all)
	inputs, _ := admissibleCorpusInputs(repo, presentAll, []string{"docs/awareness"})
	if err := AdmitPublication("github.com/acme/thing", inputs, registry); err != nil {
		t.Fatalf("admission refused a bootstrap-shaped run: %v", err)
	}
}

// The regression this must not cause: a path that exists and is NOT admitted by the
// domain is still dropped for the governance reason, not silently kept.
func TestAnExistingButInadmissibleRootIsStillDropped(t *testing.T) {
	repo := gitRepo(t, "git@github.com:acme/thing.git")
	other := filepath.Join(repo, "docs", "elsewhere")
	if err := os.MkdirAll(other, 0o755); err != nil {
		t.Fatal(err)
	}
	inputs, dropped := admissibleCorpusInputs(repo, []string{filepath.Join(repo, "docs", "awareness"), other}, []string{"docs/awareness"})
	for _, in := range inputs {
		if in == other {
			t.Errorf("an existing root the domain does not admit was kept: %s", in)
		}
	}
	if len(dropped) == 0 {
		t.Error("the inadmissible root was dropped silently")
	}
}

// The command must COMPOSE the two filters, in order. A mutant that fed allInputs straight
// to the allowlist survived the behavioural witnesses above, because they perform the
// composition themselves — the seventh instance this session of a property proven in a
// helper and unasserted at the call site.
// The RECOMPUTATION must happen after the stages that create the corpus.
//
// This replaces an earlier version of this witness that asserted the filter appeared before
// admission. That ordering was true and insufficient: it said nothing about WHEN relative to
// the stages, and the filter sat before them, so a fresh repository was refused its own
// bootstrap. Structural, and deliberately narrow -- the behavioural claim is carried by
// TestAFreshRepositoryReachesTheStageThatCreatesItsCorpus and
// TestTheImportCommandAdmitsTheRecomputedInputsAtTheLoadStep, which drive the real command.
func TestTheImportCommandRecomputesPublicationInputsAfterExtraction(t *testing.T) {
	src := readCmdSource(t, "cmd_import.go")
	extraction := strings.Index(src, "runBootstrap([]string{\"--path\", checkout")
	if extraction < 0 {
		t.Fatal("structural extraction is gone; this check has lost its anchor")
	}
	filter := strings.Index(src, "existingCorpusInputs(plannedInputs)")
	if filter < 0 {
		t.Fatal("publication inputs are no longer recomputed from the filesystem")
	}
	if filter < extraction {
		t.Errorf("the existence filter runs at %d, BEFORE extraction at %d: a fresh repository would be refused because the corpus this command creates did not exist yet",
			filter, extraction)
	}
	adm := strings.Index(src[filter:], "admissibleCorpusInputs(checkout, presentInputs")
	if adm < 0 {
		t.Error("the allowlist is not applied to the recomputed present set")
	}
	if !strings.Contains(src, "append(droppedInputs, absentInputs...)") {
		t.Error("absent roots are dropped without being reported")
	}
	// And the pre-mutation question must still be asked, before anything writes.
	pre := strings.Index(src, "admissionPossibleBeforeMutation(")
	if pre < 0 {
		t.Fatal("no pre-mutation admission check: registry and identity failures would be found only after extraction writes")
	}
	if pre > extraction {
		t.Errorf("the pre-mutation check runs at %d, AFTER extraction at %d", pre, extraction)
	}
}
