// SPDX-License-Identifier: AGPL-3.0-only

package packcustody

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

const packBody = `# Meta-Principles.
#
# GENERATED by scripts/sync-principle-pack.py — do not edit by hand.
invariants:
  - id: meta.one
    title: "One"
`

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// project creates a checkout with a state directory so the provenance paths
// resolve the way they do in a real repository.
func project(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".sensei"), 0o755); err != nil {
		t.Fatal(err)
	}
	return root
}

func writeInstall(t *testing.T, root, packDigest string) {
	t.Helper()
	var ir InstallRecord
	ir.SchemaVersion = ReceiptSchemaVersion
	ir.Kind = InstallKind
	ir.PackDigest = packDigest
	b, err := yaml.Marshal(ir)
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, InstallRecordFilePath(root), string(b))
}

func writeAdoption(t *testing.T, root, prev, resulting, packDigest, authorization string) {
	t.Helper()
	var r AdoptionRecord
	r.SchemaVersion = ReceiptSchemaVersion
	r.Kind = AdoptionKind
	r.Source.PackDigest = packDigest
	r.Target.Path = MirrorRelPath
	r.Target.PreviousDigest = prev
	r.Target.ResultingDigest = resulting
	r.Authorization = authorization
	b, err := yaml.Marshal(r)
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(AdoptionsDirPath(root), Short(resulting)+".yaml"), string(b))
}

func TestInstallRecordProvesSharedProjection(t *testing.T) {
	root := project(t)
	writeInstall(t, root, Digest([]byte(packBody)))

	v := Derive(root, []byte(packBody))
	if v.Custody != SharedProjection {
		t.Fatalf("custody = %q, want %q (%s)", v.Custody, SharedProjection, v.Describe())
	}
	if !v.Excluded() {
		t.Fatal("a shared projection must be excluded from the repository's publication")
	}
	if !strings.Contains(v.Basis, "install record") {
		t.Fatalf("basis does not name its evidence: %q", v.Basis)
	}
}

func TestAdoptionReceiptProvesSharedProjection(t *testing.T) {
	root := project(t)
	// No install record at all: the receipt alone is sufficient evidence.
	writeAdoption(t, root, "previousdigest", Digest([]byte(packBody)), "packdigest", "reconcile-legacy")

	v := Derive(root, []byte(packBody))
	if v.Custody != SharedProjection {
		t.Fatalf("custody = %q, want %q (%s)", v.Custody, SharedProjection, v.Describe())
	}
	if !strings.Contains(v.Basis, "reconcile-legacy") {
		t.Fatalf("basis must carry the authorization that admitted it: %q", v.Basis)
	}
}

// A mirror projecting an OLDER pack still has settled custody. Tying custody to
// the current canonical digest would flip every project's ownership the moment
// upstream published a principle — reintroducing the whole-graph coupling that
// made one domain's publication invalidate another's.
func TestProjectionOfAnOlderPackKeepsSettledCustody(t *testing.T) {
	root := project(t)
	oldPack := packBody
	writeInstall(t, root, Digest([]byte(oldPack)))

	// Upstream has since published a newer pack; the project has not refreshed.
	newerPack := packBody + "  - id: meta.two\n    title: \"Two\"\n"
	if Digest([]byte(oldPack)) == Digest([]byte(newerPack)) {
		t.Fatal("test setup: the two packs must differ")
	}

	if v := Derive(root, []byte(oldPack)); v.Custody != SharedProjection {
		t.Fatalf("stale-but-governed mirror: custody = %q, want %q", v.Custody, SharedProjection)
	}
}

func TestRepoAuthoredCorpusIsNotExcluded(t *testing.T) {
	root := project(t)
	writeInstall(t, root, Digest([]byte(packBody)))

	own := "invariants:\n  - id: svc.one\n    title: \"Repo knowledge\"\n"
	v := Derive(root, []byte(own))
	if v.Custody != RepoAuthored {
		t.Fatalf("custody = %q, want %q", v.Custody, RepoAuthored)
	}
	if v.Excluded() {
		t.Fatal("the repository's own knowledge must still be published")
	}
}

func TestManagedMirrorWithoutProvenanceIsRefused(t *testing.T) {
	root := project(t) // no install record, no receipts — the legacy state

	v := Derive(root, []byte(packBody))
	if v.Custody != Refused {
		t.Fatalf("custody = %q, want %q", v.Custody, Refused)
	}
	if !v.Excluded() {
		t.Fatal("a refusal must be excluded from the publication")
	}
	// The refusal must be actionable, not merely negative.
	for _, want := range []string{"no install record or adoption receipt", "principle-pack refresh", "--reconcile-legacy"} {
		if !strings.Contains(v.Reason, want) {
			t.Errorf("refusal reason missing %q; got: %s", want, v.Reason)
		}
	}
}

// A mirror that has DIVERGED from every pack it could be a projection of is
// refused, not attributed. This is the disposition that keeps the mechanism from
// being quietly relaxed into "close enough": the honest answer to "who wrote
// this?" is nobody-knows, and both guesses corrupt something.
func TestDivergedMirrorIsRefusedNotAttributed(t *testing.T) {
	root := project(t)
	writeInstall(t, root, Digest([]byte(packBody)))

	edited := strings.Replace(packBody, `title: "One"`, `title: "One, locally edited"`, 1)
	v := Derive(root, []byte(edited))
	if v.Custody != Refused {
		t.Fatalf("custody = %q, want %q — a diverged mirror must not inherit the baseline's custody", v.Custody, Refused)
	}
}

// THE forgery test. The generated marker is file content, so it is exactly as
// forgeable as the aw:repo tag this package refuses to trust as an oracle. It is
// therefore honoured in one direction only: it can cost a document its
// repository authorship, never win it shared custody.
func TestSelfDeclarationCannotForgeSharedCustody(t *testing.T) {
	root := project(t) // no governed record proves anything

	forged := "# GENERATED by scripts/sync-principle-pack.py\ninvariants:\n  - id: meta.one\n    title: \"Forged\"\n"
	v := Derive(root, []byte(forged))
	if v.Custody == SharedProjection {
		t.Fatal("content alone must never establish shared custody; only a governed record can")
	}
	if v.Custody != Refused {
		t.Fatalf("custody = %q, want %q", v.Custody, Refused)
	}
}

// The converse direction of the same asymmetry: a forged INSTALL RECORD can only
// remove the forger's own content from its own slice. It cannot inject anything
// into the shared slice, because no repository-scoped publication writes there.
// That is what makes the writability of these records non-load-bearing.
func TestForgedInstallRecordOnlyCostsTheForgerItsOwnSlice(t *testing.T) {
	root := project(t)
	locallyAuthored := "# GENERATED by scripts/sync-principle-pack.py\ninvariants:\n  - id: meta.one\n    title: \"Mine now\"\n"
	writeInstall(t, root, Digest([]byte(locallyAuthored))) // the lie

	v := Derive(root, []byte(locallyAuthored))
	if v.Custody != SharedProjection {
		t.Fatalf("custody = %q; the record is believed, but see what that buys", v.Custody)
	}
	// The whole point: the only consequence is exclusion.
	if !v.Excluded() {
		t.Fatal("a forged record must not gain the forger a publication anywhere")
	}
}

// A symlinked install record pointing into another checkout must not be read as
// this project's own evidence — that would let one repository borrow another's
// baseline to have its divergence declared verified.
func TestSymlinkedInstallRecordIsNotTrusted(t *testing.T) {
	foreign := project(t)
	writeInstall(t, foreign, Digest([]byte(packBody)))

	root := project(t)
	link := InstallRecordFilePath(root)
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(InstallRecordFilePath(foreign), link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	if v := Derive(root, []byte(packBody)); v.Custody != Refused {
		t.Fatalf("custody = %q, want %q — foreign evidence must not verify this mirror", v.Custody, Refused)
	}
}

// Custody must not be decided by where a document lives or what it is called.
// Identical content gets an identical verdict from any path, and a document named
// like the mirror gets no special treatment.
func TestCustodyIsIndependentOfPathAndFilename(t *testing.T) {
	root := project(t)
	writeInstall(t, root, Digest([]byte(packBody)))

	// Proven content is a projection wherever it sits — moving it does not
	// launder it into repository-authored knowledge.
	if v := Derive(root, []byte(packBody)); v.Custody != SharedProjection {
		t.Fatalf("proven content at any path: custody = %q", v.Custody)
	}

	// And a file that merely has the mirror's NAME earns nothing: the derivation
	// never sees a path, so this is structural rather than a checked rule.
	own := "invariants:\n  - id: svc.one\n    title: \"Repo knowledge\"\n"
	if v := Derive(root, []byte(own)); v.Custody != RepoAuthored {
		t.Fatalf("unproven, unmarked content: custody = %q, want %q", v.Custody, RepoAuthored)
	}
}

// The marker is a header. A principle whose BODY quotes the marker sentence —
// this repository's own knowledge does exactly that when documenting the
// mechanism — must not thereby declare itself generated and refuse itself.
func TestMarkerQuotedInABodyIsNotASelfDeclaration(t *testing.T) {
	root := project(t)
	quoting := `invariants:
  - id: svc.documents_the_pack
    title: "Explains the mirror"
    summary: |
      A managed mirror announces itself with the line
      "GENERATED by scripts/sync-principle-pack.py" in its header.
`
	if v := Derive(root, []byte(quoting)); v.Custody != RepoAuthored {
		t.Fatalf("custody = %q, want %q — a quotation is not a declaration (%s)", v.Custody, RepoAuthored, v.Describe())
	}
}

func TestProjectRootForFindsTheOwningCheckout(t *testing.T) {
	root := project(t)
	corpus := filepath.Join(root, "docs", "awareness")
	if err := os.MkdirAll(corpus, 0o755); err != nil {
		t.Fatal(err)
	}
	got, ok := ProjectRootFor(corpus)
	if !ok {
		t.Fatal("expected to locate the owning checkout")
	}
	// t.TempDir may hand back a symlinked path (/var -> /private/var on macOS);
	// compare resolved paths so the assertion is about the directory, not its name.
	wantResolved, _ := filepath.EvalSymlinks(root)
	gotResolved, _ := filepath.EvalSymlinks(got)
	if gotResolved != wantResolved {
		t.Fatalf("root = %q, want %q", gotResolved, wantResolved)
	}
}

// No state directory anywhere above means no governed provenance exists. That
// must be reported as absent so callers refuse, never silently treated as
// "custody is fine".
func TestProjectRootForReportsAbsenceRatherThanGuessing(t *testing.T) {
	bare := filepath.Join(t.TempDir(), "no", "state", "dir")
	if err := os.MkdirAll(bare, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, ok := ProjectRootFor(bare); ok {
		t.Fatal("a tree with no state directory must not report a custody authority")
	}
}
