// SPDX-License-Identifier: AGPL-3.0-only

// Package packcustody answers ONE question about a corpus document: who is
// allowed to publish it as their own architectural knowledge.
//
// It exists because publication ownership was being derived from the checkout
// that happened to contain a file. `sensei init` installs a MIRROR of the
// portable principle pack into every project; `sensei build --repo <domain>`
// then published that mirror tagged to that repository, because the corpus
// directory it was found in belongs to that repository. Two initialized
// projects sharing one store therefore minted two authoritative authoring
// domains for one stable identity — measured on the live topology as 143
// co-owned subjects, 134 of them pack identities.
//
// Location cannot decide custody. Neither can the graph's own aw:repo tag,
// which is writable content: a bad corpus could simply declare itself the
// author. Custody derives instead from the governed provenance chain the
// principle-pack work already established:
//
//	canonical pack digest -> install record -> adoption receipt
//	    -> this content is a proven projection of pack X
//
// This file holds that provenance state — the record shapes and the readers
// that refuse to be redirected out of the checkout. custody.go holds the
// decision built on top of them.
package packcustody

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/globulario/sensei/golang/statedir"
)

const (
	// ReceiptSchemaVersion versions both record shapes below.
	ReceiptSchemaVersion = 1

	// AdoptionKind and InstallKind are the `kind` discriminators. A document
	// that does not carry the expected kind is not read as evidence: an
	// unrelated YAML file dropped into the adoptions directory must not be
	// mistaken for a receipt.
	AdoptionKind = "principle_pack_adoption"
	InstallKind  = "principle_pack_install"

	// GeneratedMarker is how a managed mirror announces itself. It is content,
	// so it is trusted in ONE direction only — see custody.go.
	GeneratedMarker = "GENERATED by scripts/sync-principle-pack.py"

	// MirrorRelPath is where `sensei init` installs the mirror. It is used for
	// operator-facing messages and for the receipt's own `target.path` field.
	// It is deliberately NOT part of the custody decision.
	MirrorRelPath = "docs/awareness/meta_principles.yaml"
)

// AdoptionRecord is BOTH the adoption intent and, once the mirror matches, the
// receipt. It is written ONCE, before the mirror is touched, and never
// rewritten. Its terminal disposition is DERIVED by digesting the mirror rather
// than stored — a stored status would be a second mutable write that can fail
// independently, which is exactly the partial-apply hole.
//
// The nested structs are inline rather than named so the emitted YAML stays
// byte-identical to records already written on disk by earlier versions.
type AdoptionRecord struct {
	SchemaVersion int    `yaml:"schema_version"`
	Kind          string `yaml:"kind"`
	Source        struct {
		Authority      string `yaml:"authority"`
		SenseiRevision string `yaml:"sensei_revision"`
		PackDigest     string `yaml:"pack_digest_sha256"`
		PrincipleCount int    `yaml:"principle_count"`
	} `yaml:"source"`
	Target struct {
		Path            string `yaml:"path"`
		PreviousDigest  string `yaml:"previous_digest_sha256"`
		ResultingDigest string `yaml:"resulting_digest_sha256"`
	} `yaml:"target"`
	Change struct {
		AddedIDs       []string `yaml:"added_ids"`
		ChangedIDs     []string `yaml:"changed_ids"`
		RemovedIDs     []string `yaml:"removed_ids"`
		ConflictingIDs []string `yaml:"conflicting_ids"`
	} `yaml:"change"`
	Authorization  string `yaml:"authorization"`
	DispositionIs  string `yaml:"disposition_is"`
	DispositionKey string `yaml:"disposition_rule"`
}

// DerivedDisposition answers "what happened?" from the mirror itself.
func (r AdoptionRecord) DerivedDisposition(mirrorDigest string) string {
	switch mirrorDigest {
	case r.Target.ResultingDigest:
		return "applied"
	case r.Target.PreviousDigest:
		return "intent_open" // record written, mirror not yet replaced
	default:
		return "conflict" // mirror is neither end of this transaction
	}
}

// InstallRecord is the baseline `sensei init` writes: the exact pack the
// project was initialized from.
type InstallRecord struct {
	SchemaVersion int      `yaml:"schema_version"`
	Kind          string   `yaml:"kind"`
	PackDigest    string   `yaml:"pack_digest_sha256"`
	PrincipleIDs  []string `yaml:"principle_ids"`
}

// The principle-pack state lives under the project's ACTIVE state directory
// (statedir.Path — ".sensei", or a pre-existing ".awg" for a legacy repo),
// never a hard-coded ".sensei/..." literal. A literal would create
// ".sensei/principle-pack" even on a repo that only has ".awg", and
// statedir.Name prefers ".sensei" once any directory exists under it — so the
// next command to resolve state would silently stop reading the project's real
// ".awg" configuration. Split-brain, from one hard-coded path.
func DirPath(root string) string {
	return filepath.Join(statedir.Path(root), "principle-pack")
}

func AdoptionsDirPath(root string) string {
	return filepath.Join(DirPath(root), "adoptions")
}

func InstallRecordFilePath(root string) string {
	return filepath.Join(DirPath(root), "installed.yaml")
}

func RefreshLockFilePath(root string) string {
	return filepath.Join(DirPath(root), "refresh.lock")
}

// LoadInstallRecord reads the install baseline. A missing or unreadable record
// is reported as absent, not as an error: "this project has no baseline" is a
// normal, expected state that callers must handle as a refusal to guess.
func LoadInstallRecord(root string) (InstallRecord, bool) {
	// ReadNoFollow, not a plain ReadFile: a symlinked installed.yaml pointing
	// at another checkout's real install record must not be followed and
	// trusted as this project's own verified baseline.
	b, err := ReadNoFollow(root, InstallRecordFilePath(root))
	if err != nil {
		return InstallRecord{}, false
	}
	var ir InstallRecord
	if yaml.Unmarshal(b, &ir) != nil || ir.Kind != InstallKind {
		return InstallRecord{}, false
	}
	return ir, true
}

// LoadAdoptionRecords reads every adoption receipt in the project.
func LoadAdoptionRecords(root string) []AdoptionRecord {
	matches, _ := filepath.Glob(filepath.Join(AdoptionsDirPath(root), "*.yaml"))
	var out []AdoptionRecord
	for _, m := range matches {
		// ReadNoFollow: a symlinked receipt is the same class of risk as a
		// symlinked baseline — refuse it rather than trust adoption "evidence"
		// that actually lives outside this checkout.
		b, err := ReadNoFollow(root, m)
		if err != nil {
			continue
		}
		var r AdoptionRecord
		if yaml.Unmarshal(b, &r) == nil && r.Kind == AdoptionKind {
			out = append(out, r)
		}
	}
	return out
}

// ReadNoFollow reads path after refusing every symlink between root and path,
// INCLUDING the leaf itself -- not just the leaf, and not just the ancestors.
// Any file this repo treats as authoritative evidence of its own state (the
// mirror, the install baseline, an adoption receipt) must be read this way: a
// symlinked ancestor OR leaf would otherwise let a read (and a later write,
// for paths callers also write to) silently redirect outside root -- including,
// concretely, into another checkout's real governance state.
func ReadNoFollow(root, path string) ([]byte, error) {
	if err := RefuseSymlinkedAncestors(root, path); err != nil {
		return nil, err
	}
	fi, err := os.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("no file at %s (%v)", path, err)
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s is a symlink; refusing to read through it", path)
	}
	if !fi.Mode().IsRegular() {
		return nil, fmt.Errorf("%s is not a regular file", path)
	}
	return os.ReadFile(path)
}

// RefuseSymlinkedAncestors Lstats every directory component strictly between
// root and path (exclusive of both), refusing if any is a symlink or anything
// other than a real directory. path itself is not checked here -- callers Lstat
// the leaf separately, since leaf handling differs (a file for the mirror, a
// directory for state-dir creation).
func RefuseSymlinkedAncestors(root, path string) error {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return fmt.Errorf("resolve %s relative to %s: %w", path, root, err)
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("%s escapes %s", path, root)
	}
	dir := filepath.Dir(rel)
	if dir == "." {
		return nil // leaf lives directly under root, nothing intermediate to check
	}
	cur := root
	for _, part := range strings.Split(dir, string(filepath.Separator)) {
		cur = filepath.Join(cur, part)
		fi, err := os.Lstat(cur)
		if err != nil {
			if os.IsNotExist(err) {
				// Not there yet is fine -- callers preparing to create a
				// directory tree (mkdirAllSynced) legitimately hit this;
				// nothing deeper can exist either, so there is nothing
				// further to check.
				return nil
			}
			return fmt.Errorf("checking ancestor %s: %w", cur, err)
		}
		if fi.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s is a symlink; refusing to read or write through it", cur)
		}
		if !fi.IsDir() {
			return fmt.Errorf("%s is not a directory", cur)
		}
	}
	return nil
}

// Digest is the content identity used throughout custody derivation.
func Digest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// Short abbreviates a digest for operator-facing messages.
func Short(s string) string {
	if len(s) > 12 {
		return s[:12]
	}
	return s
}

// ProjectRootFor locates the project whose governed records decide custody for a
// corpus directory, by walking up to the nearest ancestor that actually has a
// state directory.
//
// It walks rather than taking the root from the caller because a corpus root can
// be supplied from anywhere — a --input pointed at a second checkout, a staged
// mirror — and the records that govern a document belong to the repository that
// contains it, not to whichever repository invoked the build. Reading one
// checkout's corpus against another checkout's install record is how a mirror
// gets declared "verified" on evidence that was never about it.
//
// A directory with no such ancestor has no governed provenance at all, which is
// reported as absent. Callers must treat that as "cannot prove custody", never
// as "custody is fine".
func ProjectRootFor(corpusDir string) (string, bool) {
	dir, err := filepath.Abs(corpusDir)
	if err != nil {
		return "", false
	}
	for {
		if isRealDir(filepath.Join(dir, statedir.DefaultName)) || isRealDir(filepath.Join(dir, statedir.LegacyName)) {
			return dir, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

func isRealDir(p string) bool {
	fi, err := os.Lstat(p)
	return err == nil && fi.IsDir()
}
